@echo off
echo Stopping postgres container...
docker stop cendia-postgres 2>nul
echo Removing container...
docker rm cendia-postgres 2>nul
echo Listing volumes...
docker volume ls
echo.
echo Creating fresh postgres with known password...
docker run -d --name cendia-postgres -e POSTGRES_USER=cendia -e POSTGRES_PASSWORD=cendia_sovereign_2025 -e POSTGRES_DB=datacendia -p 5432:5432 postgres:16-alpine
echo Done! Waiting 5 seconds for startup...
timeout /t 5 /nobreak
echo Testing connection...
docker exec -e PGPASSWORD=cendia_sovereign_2025 cendia-postgres psql -U cendia -d datacendia -c "SELECT 1;"
