/**
 * Service Registry — Full Platform (All Tiers)
 *
 * Catalogs ALL available Datacendia services for the workflow builder.
 * Components (Full Platform) includes Foundation + Enterprise + Strategic.
 *
 * @exports SERVICE_REGISTRY, getServiceById, getServicesByCategory, getServicesByTier
 * @module services/ServiceRegistry
 */

// Copyright (c) 2024-2026 Datacendia, LLC. Licensed under Apache 2.0.
// See LICENSE file for details.

import type { ServiceDefinition, ServiceCategory, ServiceTier } from '../types/workflow';

// =============================================================================
// ALL SERVICES — FOUNDATION + ENTERPRISE + STRATEGIC
// =============================================================================

export const SERVICE_REGISTRY: ServiceDefinition[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // FOUNDATION TIER
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Council ────────────────────────────────────────────────────────────────
  {
    id: 'council-deliberation',
    name: 'Council Deliberation',
    shortName: 'Deliberate',
    description: 'Multi-agent deliberation — pose a question and let agents analyze, debate, and reach consensus',
    category: 'council',
    tier: 'foundation',
    icon: 'Users',
    color: 'cyan',
    inputs: [
      { id: 'question', name: 'Question', type: 'data', description: 'The decision question to deliberate' },
      { id: 'context', name: 'Context', type: 'data', description: 'Optional background context' },
    ],
    outputs: [
      { id: 'decision', name: 'Decision', type: 'decision', description: 'The deliberated decision with rationale' },
      { id: 'score', name: 'Confidence Score', type: 'score', description: 'Consensus confidence 0-100' },
    ],
    configSchema: [
      { key: 'mode', label: 'Deliberation Mode', type: 'select', defaultValue: 'standard', options: [{ label: 'Standard', value: 'standard' }, { label: 'Adversarial', value: 'adversarial' }, { label: 'Consensus', value: 'consensus' }] },
      { key: 'maxRounds', label: 'Max Rounds', type: 'number', defaultValue: 5 },
      { key: 'requireUnanimity', label: 'Require Unanimity', type: 'boolean', defaultValue: false },
    ],
  },
  {
    id: 'council-replay',
    name: 'CendiaReplay™',
    shortName: 'Replay',
    description: 'Replay a past deliberation to review agent reasoning and decision evolution',
    category: 'council',
    tier: 'foundation',
    icon: 'Film',
    color: 'cyan',
    inputs: [{ id: 'deliberationId', name: 'Deliberation ID', type: 'data' }],
    outputs: [{ id: 'replay', name: 'Replay Data', type: 'data' }],
    configSchema: [{ key: 'speed', label: 'Playback Speed', type: 'select', defaultValue: '1x', options: [{ label: '0.5x', value: '0.5x' }, { label: '1x', value: '1x' }, { label: '2x', value: '2x' }] }],
  },
  {
    id: 'council-executive-summary',
    name: 'Executive Summary',
    shortName: 'Summary',
    description: 'Generate a board-ready executive summary from a deliberation',
    category: 'council',
    tier: 'foundation',
    icon: 'FileText',
    color: 'cyan',
    inputs: [{ id: 'deliberation', name: 'Deliberation', type: 'decision' }],
    outputs: [{ id: 'report', name: 'Executive Report', type: 'report' }],
    configSchema: [{ key: 'format', label: 'Format', type: 'select', defaultValue: 'pdf', options: [{ label: 'PDF', value: 'pdf' }, { label: 'Markdown', value: 'md' }, { label: 'HTML', value: 'html' }] }],
  },

  // ── DECIDE Intelligence (Foundation) ───────────────────────────────────────
  {
    id: 'chronos',
    name: 'CendiaChronos™',
    shortName: 'Chronos',
    description: 'Enterprise time machine — timeline analysis, pivotal moment detection, multi-branch comparison',
    category: 'intelligence',
    tier: 'foundation',
    icon: 'Clock',
    color: 'violet',
    inputs: [{ id: 'entityId', name: 'Entity or Decision ID', type: 'data' }],
    outputs: [{ id: 'timeline', name: 'Timeline', type: 'data' }, { id: 'pivotalMoments', name: 'Pivotal Moments', type: 'data' }],
    configSchema: [
      { key: 'dateRange', label: 'Date Range', type: 'select', defaultValue: '90d', options: [{ label: '30 days', value: '30d' }, { label: '90 days', value: '90d' }, { label: '1 year', value: '1y' }, { label: 'All time', value: 'all' }] },
      { key: 'enableDiff', label: 'Enable Diff View', type: 'boolean', defaultValue: true },
    ],
  },
  {
    id: 'pre-mortem',
    name: 'PreMortem Analysis',
    shortName: 'PreMortem',
    description: 'Anticipate failure modes before a decision is finalized',
    category: 'intelligence',
    tier: 'foundation',
    icon: 'Skull',
    color: 'violet',
    inputs: [{ id: 'decision', name: 'Proposed Decision', type: 'decision' }],
    outputs: [{ id: 'risks', name: 'Risk Factors', type: 'data' }, { id: 'score', name: 'Risk Score', type: 'score' }],
    configSchema: [{ key: 'depth', label: 'Analysis Depth', type: 'select', defaultValue: 'standard', options: [{ label: 'Quick', value: 'quick' }, { label: 'Standard', value: 'standard' }, { label: 'Deep', value: 'deep' }] }],
  },
  {
    id: 'ghost-board',
    name: 'Ghost Board',
    shortName: 'GhostBoard',
    description: 'Simulate board-level review of a decision with synthetic directors',
    category: 'intelligence',
    tier: 'foundation',
    icon: 'Ghost',
    color: 'violet',
    inputs: [{ id: 'decision', name: 'Decision', type: 'decision' }],
    outputs: [{ id: 'boardReview', name: 'Board Review', type: 'report' }],
    configSchema: [{ key: 'boardSize', label: 'Board Size', type: 'number', defaultValue: 5 }],
  },
  {
    id: 'decision-debt',
    name: 'Decision Debt Tracker',
    shortName: 'DecisionDebt',
    description: 'Track accumulated decision debt — deferred, stale, or unresolved decisions',
    category: 'intelligence',
    tier: 'foundation',
    icon: 'TrendingUp',
    color: 'violet',
    inputs: [{ id: 'scope', name: 'Scope', type: 'data' }],
    outputs: [{ id: 'debtReport', name: 'Debt Report', type: 'report' }, { id: 'score', name: 'Debt Score', type: 'score' }],
    configSchema: [{ key: 'threshold', label: 'Staleness Threshold (days)', type: 'number', defaultValue: 30 }],
  },

  // ── DCII (Foundation) ──────────────────────────────────────────────────────
  {
    id: 'dcii-truth',
    name: 'DCII Truth Verification',
    shortName: 'Truth',
    description: 'Verify factual claims and detect hallucinations in AI outputs',
    category: 'dcii',
    tier: 'foundation',
    icon: 'CheckCircle',
    color: 'emerald',
    inputs: [{ id: 'content', name: 'Content to Verify', type: 'data' }],
    outputs: [{ id: 'truthScore', name: 'Truth Score', type: 'score' }, { id: 'evidence', name: 'Evidence', type: 'evidence' }],
    configSchema: [{ key: 'strictness', label: 'Strictness', type: 'select', defaultValue: 'standard', options: [{ label: 'Lenient', value: 'lenient' }, { label: 'Standard', value: 'standard' }, { label: 'Strict', value: 'strict' }] }],
  },
  {
    id: 'dcii-notary',
    name: 'DCII Notary',
    shortName: 'Notary',
    description: 'Cryptographically sign and notarize decisions for immutable audit trails',
    category: 'dcii',
    tier: 'foundation',
    icon: 'FileSignature',
    color: 'emerald',
    inputs: [{ id: 'decision', name: 'Decision', type: 'decision' }],
    outputs: [{ id: 'certificate', name: 'Notary Certificate', type: 'evidence' }],
    configSchema: [{ key: 'algorithm', label: 'Signing Algorithm', type: 'select', defaultValue: 'ed25519', options: [{ label: 'Ed25519', value: 'ed25519' }, { label: 'RSA-2048', value: 'rsa-2048' }, { label: 'Dilithium (PQ)', value: 'dilithium' }] }],
  },
  {
    id: 'dcii-witness',
    name: 'DCII Witness',
    shortName: 'Witness',
    description: 'Independent witnessing of deliberation process with tamper-proof logging',
    category: 'dcii',
    tier: 'foundation',
    icon: 'Eye',
    color: 'emerald',
    inputs: [{ id: 'deliberation', name: 'Deliberation', type: 'decision' }],
    outputs: [{ id: 'witnessLog', name: 'Witness Log', type: 'evidence' }],
    configSchema: [],
  },
  {
    id: 'dcii-timestamp',
    name: 'DCII Timestamp',
    shortName: 'Timestamp',
    description: 'RFC 3161 compliant timestamping for evidence chain integrity',
    category: 'dcii',
    tier: 'foundation',
    icon: 'Clock',
    color: 'emerald',
    inputs: [{ id: 'document', name: 'Document', type: 'any' }],
    outputs: [{ id: 'timestamp', name: 'Timestamp Token', type: 'evidence' }],
    configSchema: [{ key: 'tsa', label: 'TSA Provider', type: 'select', defaultValue: 'internal', options: [{ label: 'Internal TSA', value: 'internal' }, { label: 'DigiCert', value: 'digicert' }] }],
  },
  {
    id: 'dcii-similarity',
    name: 'DCII Similarity',
    shortName: 'Similarity',
    description: 'Detect similar past decisions and precedent patterns',
    category: 'dcii',
    tier: 'foundation',
    icon: 'Search',
    color: 'emerald',
    inputs: [{ id: 'decision', name: 'Decision', type: 'decision' }],
    outputs: [{ id: 'matches', name: 'Similar Decisions', type: 'data' }, { id: 'score', name: 'Similarity Score', type: 'score' }],
    configSchema: [{ key: 'minScore', label: 'Min Similarity %', type: 'number', defaultValue: 70 }],
  },
  {
    id: 'dcii-memory',
    name: 'DCII Memory',
    shortName: 'Memory',
    description: 'Institutional memory — long-term knowledge retention and retrieval',
    category: 'dcii',
    tier: 'foundation',
    icon: 'Brain',
    color: 'emerald',
    inputs: [{ id: 'query', name: 'Query', type: 'data' }],
    outputs: [{ id: 'memories', name: 'Retrieved Memories', type: 'data' }],
    configSchema: [{ key: 'limit', label: 'Max Results', type: 'number', defaultValue: 10 }],
  },

  // ── Gateway (Foundation) ───────────────────────────────────────────────────
  {
    id: 'gateway',
    name: 'CendiaGateway™',
    shortName: 'Gateway',
    description: 'AI governance proxy — PII detection, policy enforcement, rate limiting',
    category: 'gateway',
    tier: 'foundation',
    icon: 'Shield',
    color: 'blue',
    inputs: [{ id: 'request', name: 'AI Request', type: 'data' }],
    outputs: [{ id: 'response', name: 'Governed Response', type: 'data' }, { id: 'piiDetections', name: 'PII Detections', type: 'alert' }, { id: 'policyBlocks', name: 'Policy Violations', type: 'alert' }],
    configSchema: [{ key: 'piiDetection', label: 'PII Detection', type: 'boolean', defaultValue: true }, { key: 'policyEnforcement', label: 'Policy Enforcement', type: 'boolean', defaultValue: true }],
  },

  // ── Graph (Foundation) ─────────────────────────────────────────────────────
  {
    id: 'graph-explorer',
    name: 'Knowledge Graph',
    shortName: 'Graph',
    description: 'Decision knowledge graph — entity relationships, lineage, and impact analysis',
    category: 'graph',
    tier: 'foundation',
    icon: 'Network',
    color: 'orange',
    inputs: [{ id: 'entityId', name: 'Entity ID', type: 'data' }],
    outputs: [{ id: 'graph', name: 'Graph Data', type: 'data' }, { id: 'lineage', name: 'Lineage', type: 'data' }],
    configSchema: [{ key: 'depth', label: 'Traversal Depth', type: 'number', defaultValue: 3 }],
  },

  // ── Pulse (Foundation) ─────────────────────────────────────────────────────
  {
    id: 'pulse-health',
    name: 'CendiaPulse™ Health',
    shortName: 'Health',
    description: 'Real-time system health monitoring — health score, latency, data freshness',
    category: 'pulse',
    tier: 'foundation',
    icon: 'HeartPulse',
    color: 'rose',
    inputs: [],
    outputs: [{ id: 'healthScore', name: 'Health Score', type: 'score' }, { id: 'alerts', name: 'Alerts', type: 'alert' }],
    configSchema: [{ key: 'interval', label: 'Check Interval (sec)', type: 'number', defaultValue: 30 }],
  },
  {
    id: 'pulse-alerts',
    name: 'CendiaPulse™ Alerts',
    shortName: 'Alerts',
    description: 'Anomaly detection and alert management',
    category: 'pulse',
    tier: 'foundation',
    icon: 'AlertTriangle',
    color: 'rose',
    inputs: [{ id: 'metrics', name: 'Metrics', type: 'data' }],
    outputs: [{ id: 'alerts', name: 'Anomaly Alerts', type: 'alert' }],
    configSchema: [{ key: 'sensitivity', label: 'Sensitivity', type: 'select', defaultValue: 'medium', options: [{ label: 'Low', value: 'low' }, { label: 'Medium', value: 'medium' }, { label: 'High', value: 'high' }] }],
  },
  {
    id: 'compliance-readiness',
    name: 'Compliance Readiness',
    shortName: 'Readiness',
    description: 'Foundation compliance overview — framework status and readiness checklist',
    category: 'compliance',
    tier: 'foundation',
    icon: 'FileCheck',
    color: 'indigo',
    inputs: [],
    outputs: [{ id: 'readinessScore', name: 'Readiness Score', type: 'score' }, { id: 'report', name: 'Readiness Report', type: 'report' }],
    configSchema: [],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ENTERPRISE TIER
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Enterprise Intelligence ────────────────────────────────────────────────
  {
    id: 'lens',
    name: 'CendiaLens™',
    shortName: 'Lens',
    description: 'Multi-dimensional decision analysis — fairness, bias, drift, and impact scoring',
    category: 'intelligence',
    tier: 'enterprise',
    icon: 'ScanEye',
    color: 'violet',
    inputs: [{ id: 'decision', name: 'Decision', type: 'decision' }],
    outputs: [{ id: 'analysis', name: 'Lens Analysis', type: 'report' }, { id: 'scores', name: 'Dimension Scores', type: 'score' }],
    configSchema: [{ key: 'dimensions', label: 'Dimensions', type: 'select', defaultValue: 'all', options: [{ label: 'All', value: 'all' }, { label: 'Fairness Only', value: 'fairness' }, { label: 'Bias Only', value: 'bias' }] }],
  },
  {
    id: 'decision-dna',
    name: 'Decision DNA',
    shortName: 'DNA',
    description: 'Extract and compare the genetic signature of decisions — patterns, precedents, lineage',
    category: 'intelligence',
    tier: 'enterprise',
    icon: 'Dna',
    color: 'violet',
    inputs: [{ id: 'decision', name: 'Decision', type: 'decision' }],
    outputs: [{ id: 'dna', name: 'DNA Profile', type: 'data' }, { id: 'matches', name: 'Pattern Matches', type: 'data' }],
    configSchema: [],
  },
  {
    id: 'what-if',
    name: 'What-If Simulator',
    shortName: 'What-If',
    description: 'Simulate alternate decision paths and compare projected outcomes',
    category: 'intelligence',
    tier: 'enterprise',
    icon: 'GitBranch',
    color: 'violet',
    inputs: [{ id: 'decision', name: 'Base Decision', type: 'decision' }, { id: 'parameters', name: 'Altered Parameters', type: 'data' }],
    outputs: [{ id: 'scenarios', name: 'Scenario Results', type: 'data' }, { id: 'comparison', name: 'Comparison Report', type: 'report' }],
    configSchema: [{ key: 'scenarioCount', label: 'Number of Scenarios', type: 'number', defaultValue: 3 }],
  },
  {
    id: 'orbit',
    name: 'CendiaOrbit™',
    shortName: 'Orbit',
    description: 'Decision orbit visualization — stakeholder gravity and influence mapping',
    category: 'intelligence',
    tier: 'enterprise',
    icon: 'Radar',
    color: 'violet',
    inputs: [{ id: 'decision', name: 'Decision', type: 'decision' }],
    outputs: [{ id: 'orbitMap', name: 'Orbit Map', type: 'data' }],
    configSchema: [],
  },
  {
    id: 'consensus',
    name: 'CendiaConsensus™',
    shortName: 'Consensus',
    description: 'Advanced consensus algorithms — weighted voting, ranked choice, quadratic',
    category: 'intelligence',
    tier: 'enterprise',
    icon: 'Target',
    color: 'violet',
    inputs: [{ id: 'options', name: 'Decision Options', type: 'data' }, { id: 'votes', name: 'Votes', type: 'data' }],
    outputs: [{ id: 'result', name: 'Consensus Result', type: 'decision' }, { id: 'breakdown', name: 'Vote Breakdown', type: 'data' }],
    configSchema: [{ key: 'algorithm', label: 'Algorithm', type: 'select', defaultValue: 'weighted', options: [{ label: 'Weighted', value: 'weighted' }, { label: 'Ranked Choice', value: 'ranked' }, { label: 'Quadratic', value: 'quadratic' }] }],
  },
  {
    id: 'synthesis',
    name: 'CendiaSynthesis™',
    shortName: 'Synthesis',
    description: 'Synthesize multiple deliberations into a unified strategic recommendation',
    category: 'intelligence',
    tier: 'enterprise',
    icon: 'Layers',
    color: 'violet',
    inputs: [{ id: 'deliberations', name: 'Deliberation Set', type: 'data' }],
    outputs: [{ id: 'synthesis', name: 'Synthesized Report', type: 'report' }],
    configSchema: [],
  },
  {
    id: 'regulatory-absorb',
    name: 'Regulatory Absorb',
    shortName: 'RegAbsorb',
    description: 'Auto-ingest regulatory changes and assess organizational impact',
    category: 'intelligence',
    tier: 'enterprise',
    icon: 'ScrollText',
    color: 'violet',
    inputs: [{ id: 'regulation', name: 'Regulation', type: 'data' }],
    outputs: [{ id: 'impact', name: 'Impact Assessment', type: 'report' }, { id: 'actions', name: 'Required Actions', type: 'data' }],
    configSchema: [{ key: 'jurisdiction', label: 'Jurisdiction', type: 'select', defaultValue: 'us', options: [{ label: 'US', value: 'us' }, { label: 'EU', value: 'eu' }, { label: 'UK', value: 'uk' }, { label: 'Global', value: 'global' }] }],
  },

  // ── Enterprise Compliance ──────────────────────────────────────────────────
  {
    id: 'continuous-compliance',
    name: 'Continuous Compliance Monitor',
    shortName: 'Comply',
    description: 'Real-time compliance monitoring across EU AI Act, NIST, ISO 42001, SOC 2, and more',
    category: 'compliance',
    tier: 'enterprise',
    icon: 'Activity',
    color: 'indigo',
    inputs: [{ id: 'scope', name: 'Monitoring Scope', type: 'data' }],
    outputs: [{ id: 'status', name: 'Compliance Status', type: 'report' }, { id: 'violations', name: 'Violations', type: 'alert' }],
    configSchema: [{ key: 'frameworks', label: 'Frameworks', type: 'select', defaultValue: 'all', options: [{ label: 'All', value: 'all' }, { label: 'EU AI Act', value: 'eu-ai-act' }, { label: 'NIST AI RMF', value: 'nist' }, { label: 'ISO 42001', value: 'iso-42001' }] }],
  },
  {
    id: 'gap-scanner',
    name: 'CendiaGapScan™',
    shortName: 'GapScan',
    description: 'Compliance gap analysis across 8 frameworks — identifies missing controls and remediation paths',
    category: 'compliance',
    tier: 'enterprise',
    icon: 'SearchCode',
    color: 'indigo',
    inputs: [{ id: 'framework', name: 'Target Framework', type: 'data' }],
    outputs: [{ id: 'gaps', name: 'Gap Report', type: 'report' }, { id: 'score', name: 'Coverage Score', type: 'score' }],
    configSchema: [{ key: 'framework', label: 'Framework', type: 'select', defaultValue: 'eu-ai-act', options: [{ label: 'EU AI Act', value: 'eu-ai-act' }, { label: 'NIST AI RMF', value: 'nist' }, { label: 'ISO 42001', value: 'iso-42001' }, { label: 'SOC 2', value: 'soc2' }] }],
  },
  {
    id: 'cross-jurisdiction',
    name: 'Cross-Jurisdiction Compliance',
    shortName: 'CrossJuris',
    description: 'Compare compliance requirements across multiple jurisdictions simultaneously',
    category: 'compliance',
    tier: 'enterprise',
    icon: 'Globe',
    color: 'indigo',
    inputs: [{ id: 'jurisdictions', name: 'Jurisdictions', type: 'data' }],
    outputs: [{ id: 'comparison', name: 'Jurisdiction Comparison', type: 'report' }],
    configSchema: [],
  },
  {
    id: 'regulatory-sandbox',
    name: 'Regulatory Sandbox',
    shortName: 'Sandbox',
    description: 'Safe testing environment for regulatory compliance scenarios',
    category: 'compliance',
    tier: 'enterprise',
    icon: 'FlaskConical',
    color: 'indigo',
    inputs: [{ id: 'scenario', name: 'Test Scenario', type: 'data' }],
    outputs: [{ id: 'result', name: 'Sandbox Result', type: 'report' }],
    configSchema: [],
  },

  // ── Governance ─────────────────────────────────────────────────────────────
  {
    id: 'decision-packets',
    name: 'Decision Packets',
    shortName: 'Packets',
    description: 'Board-ready decision packages with evidence, analysis, and recommendations',
    category: 'governance',
    tier: 'enterprise',
    icon: 'Briefcase',
    color: 'amber',
    inputs: [{ id: 'deliberation', name: 'Deliberation', type: 'decision' }],
    outputs: [{ id: 'packet', name: 'Decision Packet', type: 'report' }],
    configSchema: [{ key: 'includeEvidence', label: 'Include Evidence', type: 'boolean', defaultValue: true }],
  },
  {
    id: 'constitutional-court',
    name: 'Constitutional Court',
    shortName: 'Court',
    description: 'Formal review of decisions against organizational constitution and principles',
    category: 'governance',
    tier: 'enterprise',
    icon: 'Gavel',
    color: 'amber',
    inputs: [{ id: 'decision', name: 'Decision', type: 'decision' }],
    outputs: [{ id: 'ruling', name: 'Court Ruling', type: 'decision' }, { id: 'opinion', name: 'Written Opinion', type: 'report' }],
    configSchema: [],
  },
  {
    id: 'dissent',
    name: 'Structured Dissent',
    shortName: 'Dissent',
    description: 'Structured dissent engine — devil\'s advocate, red team, and contrarian analysis',
    category: 'governance',
    tier: 'enterprise',
    icon: 'Megaphone',
    color: 'amber',
    inputs: [{ id: 'decision', name: 'Decision', type: 'decision' }],
    outputs: [{ id: 'dissents', name: 'Dissent Arguments', type: 'data' }, { id: 'strengthened', name: 'Strengthened Decision', type: 'decision' }],
    configSchema: [{ key: 'intensity', label: 'Dissent Intensity', type: 'select', defaultValue: 'moderate', options: [{ label: 'Mild', value: 'mild' }, { label: 'Moderate', value: 'moderate' }, { label: 'Aggressive', value: 'aggressive' }] }],
  },
  {
    id: 'oversight',
    name: 'CendiaOversight™',
    shortName: 'Oversight',
    description: 'Panopticon merged with Governance — full visibility into all decision processes',
    category: 'governance',
    tier: 'enterprise',
    icon: 'Eye',
    color: 'amber',
    inputs: [],
    outputs: [{ id: 'auditTrail', name: 'Audit Trail', type: 'evidence' }, { id: 'report', name: 'Oversight Report', type: 'report' }],
    configSchema: [{ key: 'scope', label: 'Scope', type: 'select', defaultValue: 'all', options: [{ label: 'All', value: 'all' }, { label: 'Last 24h', value: '24h' }, { label: 'Last 7d', value: '7d' }] }],
  },
  {
    id: 'responsibility',
    name: 'AI Responsibility',
    shortName: 'Responsibility',
    description: 'AI ethics assessment — fairness, transparency, accountability scoring',
    category: 'governance',
    tier: 'enterprise',
    icon: 'UserCheck',
    color: 'amber',
    inputs: [{ id: 'system', name: 'AI System', type: 'data' }],
    outputs: [{ id: 'assessment', name: 'Responsibility Assessment', type: 'report' }, { id: 'score', name: 'Ethics Score', type: 'score' }],
    configSchema: [],
  },

  // ── Crypto ─────────────────────────────────────────────────────────────────
  {
    id: 'escrow',
    name: 'CendiaEscrow™',
    shortName: 'Escrow',
    description: 'Shamir Secret Sharing & VDF time-locks for decision key management',
    category: 'crypto',
    tier: 'enterprise',
    icon: 'Lock',
    color: 'amber',
    inputs: [{ id: 'decision', name: 'Decision to Escrow', type: 'decision' }],
    outputs: [{ id: 'escrowId', name: 'Escrow ID', type: 'data' }, { id: 'shares', name: 'Key Shares', type: 'data' }],
    configSchema: [
      { key: 'threshold', label: 'Threshold (M of N)', type: 'number', defaultValue: 3 },
      { key: 'totalShares', label: 'Total Shares', type: 'number', defaultValue: 5 },
      { key: 'vdfDelay', label: 'VDF Delay (hours)', type: 'number', defaultValue: 24 },
    ],
  },
  {
    id: 'post-quantum-kms',
    name: 'Post-Quantum KMS',
    shortName: 'PQ-KMS',
    description: 'Quantum-resistant key management — Dilithium, SPHINCS+, Falcon signatures',
    category: 'crypto',
    tier: 'enterprise',
    icon: 'KeyRound',
    color: 'amber',
    inputs: [{ id: 'data', name: 'Data to Sign', type: 'any' }],
    outputs: [{ id: 'signature', name: 'PQ Signature', type: 'evidence' }],
    configSchema: [{ key: 'algorithm', label: 'PQ Algorithm', type: 'select', defaultValue: 'dilithium', options: [{ label: 'Dilithium', value: 'dilithium' }, { label: 'SPHINCS+', value: 'sphincs' }, { label: 'Falcon', value: 'falcon' }] }],
  },
  {
    id: 'zkp',
    name: 'Zero-Knowledge Proofs',
    shortName: 'ZKP',
    description: 'Generate and verify zero-knowledge proofs for privacy-preserving compliance',
    category: 'crypto',
    tier: 'enterprise',
    icon: 'ShieldCheck',
    color: 'amber',
    inputs: [{ id: 'claim', name: 'Claim', type: 'data' }],
    outputs: [{ id: 'proof', name: 'ZK Proof', type: 'evidence' }],
    configSchema: [{ key: 'proofSystem', label: 'Proof System', type: 'select', defaultValue: 'groth16', options: [{ label: 'Groth16', value: 'groth16' }, { label: 'PLONK', value: 'plonk' }, { label: 'STARK', value: 'stark' }] }],
  },
  {
    id: 'evidence-vault',
    name: 'Evidence Vault',
    shortName: 'Vault',
    description: 'Cryptographically sealed evidence bundles — forensic-grade, independently verifiable',
    category: 'crypto',
    tier: 'enterprise',
    icon: 'Archive',
    color: 'amber',
    inputs: [{ id: 'evidence', name: 'Evidence', type: 'evidence' }],
    outputs: [{ id: 'bundle', name: 'Sealed Bundle', type: 'evidence' }, { id: 'receipt', name: 'Storage Receipt', type: 'data' }],
    configSchema: [],
  },
  {
    id: 'ledger',
    name: 'Decision Ledger',
    shortName: 'Ledger',
    description: 'Immutable decision ledger — full decision lineage with cryptographic signatures',
    category: 'crypto',
    tier: 'enterprise',
    icon: 'ScrollText',
    color: 'amber',
    inputs: [{ id: 'decision', name: 'Decision', type: 'decision' }],
    outputs: [{ id: 'ledgerEntry', name: 'Ledger Entry', type: 'evidence' }],
    configSchema: [],
  },

  // ── Crown Jewels ───────────────────────────────────────────────────────────
  {
    id: 'crown-echo',
    name: 'CendiaEcho™',
    shortName: 'Echo',
    description: 'Decision echo chamber analysis — detect groupthink and echo effects',
    category: 'crown',
    tier: 'enterprise',
    icon: 'Radio',
    color: 'purple',
    inputs: [{ id: 'deliberations', name: 'Deliberation History', type: 'data' }],
    outputs: [{ id: 'echoScore', name: 'Echo Score', type: 'score' }, { id: 'report', name: 'Echo Report', type: 'report' }],
    configSchema: [],
  },
  {
    id: 'crown-redteam',
    name: 'CendiaRedTeam™',
    shortName: 'RedTeam',
    description: 'Adversarial red team stress testing of AI decision systems',
    category: 'crown',
    tier: 'enterprise',
    icon: 'Flame',
    color: 'purple',
    inputs: [{ id: 'system', name: 'Target System', type: 'data' }],
    outputs: [{ id: 'vulnerabilities', name: 'Vulnerabilities', type: 'alert' }, { id: 'report', name: 'Red Team Report', type: 'report' }],
    configSchema: [{ key: 'attackVectors', label: 'Attack Vectors', type: 'select', defaultValue: 'all', options: [{ label: 'All', value: 'all' }, { label: 'Prompt Injection', value: 'prompt' }, { label: 'Data Poisoning', value: 'data' }, { label: 'Model Extraction', value: 'extraction' }] }],
  },
  {
    id: 'crown-gnosis',
    name: 'CendiaGnosis™',
    shortName: 'Gnosis',
    description: 'Deep organizational knowledge extraction — hidden patterns and meta-insights',
    category: 'crown',
    tier: 'enterprise',
    icon: 'Infinity',
    color: 'purple',
    inputs: [{ id: 'corpus', name: 'Knowledge Corpus', type: 'data' }],
    outputs: [{ id: 'insights', name: 'Meta-Insights', type: 'data' }, { id: 'patterns', name: 'Hidden Patterns', type: 'data' }],
    configSchema: [],
  },

  // ── Enterprise Features ────────────────────────────────────────────────────
  {
    id: 'gateway-dashboard',
    name: 'Gateway Dashboard',
    shortName: 'GW Dashboard',
    description: 'Enterprise gateway monitoring — traffic, policies, PII detection rates',
    category: 'enterprise',
    tier: 'enterprise',
    icon: 'Shield',
    color: 'purple',
    inputs: [],
    outputs: [{ id: 'metrics', name: 'Gateway Metrics', type: 'data' }],
    configSchema: [],
  },
  {
    id: 'defense-stack',
    name: 'CendiaDefense™ Stack',
    shortName: 'Defense',
    description: 'Multi-layer AI defense stack — WAF, anomaly detection, threat intelligence',
    category: 'enterprise',
    tier: 'enterprise',
    icon: 'Shield',
    color: 'purple',
    inputs: [{ id: 'system', name: 'Target System', type: 'data' }],
    outputs: [{ id: 'threats', name: 'Threat Intelligence', type: 'alert' }, { id: 'defenseReport', name: 'Defense Report', type: 'report' }],
    configSchema: [],
  },
  {
    id: 'crisis-management',
    name: 'Crisis Management',
    shortName: 'Crisis',
    description: 'AI incident response — crisis playbooks, escalation, and containment',
    category: 'enterprise',
    tier: 'enterprise',
    icon: 'Siren',
    color: 'purple',
    inputs: [{ id: 'incident', name: 'Incident', type: 'alert' }],
    outputs: [{ id: 'response', name: 'Crisis Response Plan', type: 'report' }],
    configSchema: [{ key: 'severity', label: 'Severity', type: 'select', defaultValue: 'high', options: [{ label: 'Low', value: 'low' }, { label: 'Medium', value: 'medium' }, { label: 'High', value: 'high' }, { label: 'Critical', value: 'critical' }] }],
  },
  {
    id: 'ai-insurance',
    name: 'AI Insurance',
    shortName: 'Insurance',
    description: 'AI decision insurance — risk quantification, policy management, claims tracking',
    category: 'enterprise',
    tier: 'enterprise',
    icon: 'Banknote',
    color: 'purple',
    inputs: [{ id: 'system', name: 'AI System', type: 'data' }],
    outputs: [{ id: 'policy', name: 'Insurance Policy', type: 'report' }, { id: 'premium', name: 'Premium Estimate', type: 'score' }],
    configSchema: [],
  },
  {
    id: 'persona-forge',
    name: 'PersonaForge™',
    shortName: 'PersonaForge',
    description: 'Create and manage synthetic agent personas with customizable traits and expertise',
    category: 'enterprise',
    tier: 'enterprise',
    icon: 'PenTool',
    color: 'purple',
    inputs: [{ id: 'template', name: 'Persona Template', type: 'data' }],
    outputs: [{ id: 'persona', name: 'Agent Persona', type: 'data' }],
    configSchema: [{ key: 'expertise', label: 'Expertise Domain', type: 'text', placeholder: 'e.g., Financial Regulation' }],
  },
  {
    id: 'carbon-aware',
    name: 'Carbon-Aware Scheduler',
    shortName: 'Carbon',
    description: 'Schedule AI workloads based on carbon intensity — minimize environmental impact',
    category: 'enterprise',
    tier: 'enterprise',
    icon: 'Leaf',
    color: 'purple',
    inputs: [{ id: 'workload', name: 'Workload', type: 'data' }],
    outputs: [{ id: 'schedule', name: 'Optimal Schedule', type: 'data' }, { id: 'carbonSaved', name: 'Carbon Saved', type: 'score' }],
    configSchema: [{ key: 'region', label: 'Region', type: 'select', defaultValue: 'us-east', options: [{ label: 'US East', value: 'us-east' }, { label: 'US West', value: 'us-west' }, { label: 'EU West', value: 'eu-west' }, { label: 'Asia Pacific', value: 'ap-southeast' }] }],
  },
  {
    id: 'omni-translate',
    name: 'OmniTranslate™',
    shortName: 'Translate',
    description: '100-language enterprise translator for decision documents and reports',
    category: 'enterprise',
    tier: 'enterprise',
    icon: 'Languages',
    color: 'purple',
    inputs: [{ id: 'content', name: 'Content', type: 'data' }, { id: 'targetLang', name: 'Target Language', type: 'data' }],
    outputs: [{ id: 'translated', name: 'Translated Content', type: 'data' }],
    configSchema: [{ key: 'targetLang', label: 'Target Language', type: 'text', placeholder: 'e.g., es, fr, de, ja' }],
  },
  {
    id: 'apotheosis',
    name: 'CendiaApotheosis™',
    shortName: 'Apotheosis',
    description: 'Ascended decision intelligence — meta-learning, emergent strategy, wisdom engine',
    category: 'enterprise',
    tier: 'enterprise',
    icon: 'Trophy',
    color: 'purple',
    inputs: [{ id: 'corpus', name: 'Decision History', type: 'data' }],
    outputs: [{ id: 'strategy', name: 'Emergent Strategy', type: 'report' }, { id: 'wisdom', name: 'Wisdom Insights', type: 'data' }],
    configSchema: [],
  },

  // ── Verticals ──────────────────────────────────────────────────────────────
  {
    id: 'vertical-healthcare',
    name: 'Healthcare Vertical',
    shortName: 'Healthcare',
    description: 'Healthcare-specialized AI governance — HIPAA, clinical decision support, patient safety',
    category: 'verticals',
    tier: 'enterprise',
    icon: 'HeartPulse',
    color: 'teal',
    inputs: [{ id: 'clinicalData', name: 'Clinical Data', type: 'data' }],
    outputs: [{ id: 'recommendation', name: 'Clinical Recommendation', type: 'decision' }, { id: 'compliance', name: 'HIPAA Status', type: 'report' }],
    configSchema: [{ key: 'specialty', label: 'Medical Specialty', type: 'text', placeholder: 'e.g., Oncology, Cardiology' }],
  },
  {
    id: 'vertical-finance',
    name: 'Financial Services Vertical',
    shortName: 'Finance',
    description: 'Financial services AI governance — SEC, MiFID II, Basel III compliance',
    category: 'verticals',
    tier: 'enterprise',
    icon: 'Banknote',
    color: 'teal',
    inputs: [{ id: 'financialData', name: 'Financial Data', type: 'data' }],
    outputs: [{ id: 'analysis', name: 'Financial Analysis', type: 'report' }, { id: 'risk', name: 'Risk Assessment', type: 'score' }],
    configSchema: [],
  },
  {
    id: 'vertical-legal',
    name: 'Legal Services Vertical',
    shortName: 'Legal',
    description: 'Legal AI governance — case analysis, regulatory tracking, compliance automation',
    category: 'verticals',
    tier: 'enterprise',
    icon: 'Gavel',
    color: 'teal',
    inputs: [{ id: 'legalQuery', name: 'Legal Query', type: 'data' }],
    outputs: [{ id: 'analysis', name: 'Legal Analysis', type: 'report' }, { id: 'precedents', name: 'Precedents', type: 'data' }],
    configSchema: [],
  },
  {
    id: 'vertical-government',
    name: 'Government & Defense Vertical',
    shortName: 'Government',
    description: 'Government AI governance — FedRAMP, FISMA, security clearance compliance',
    category: 'verticals',
    tier: 'enterprise',
    icon: 'Landmark',
    color: 'teal',
    inputs: [{ id: 'policyData', name: 'Policy Data', type: 'data' }],
    outputs: [{ id: 'assessment', name: 'Policy Assessment', type: 'report' }],
    configSchema: [],
  },
  {
    id: 'vertical-pharma',
    name: 'Pharmaceutical Vertical',
    shortName: 'Pharma',
    description: 'Pharma AI governance — FDA, EMA, clinical trial AI, drug discovery compliance',
    category: 'verticals',
    tier: 'enterprise',
    icon: 'Pill',
    color: 'teal',
    inputs: [{ id: 'trialData', name: 'Clinical Trial Data', type: 'data' }],
    outputs: [{ id: 'assessment', name: 'Regulatory Assessment', type: 'report' }],
    configSchema: [],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STRATEGIC TIER
  // ═══════════════════════════════════════════════════════════════════════════

  // ── Sovereign ──────────────────────────────────────────────────────────────
  {
    id: 'collapse',
    name: 'COLLAPSE™',
    shortName: 'COLLAPSE',
    description: 'Adversarial policy stress-testing — simulate systemic failures and cascading collapses',
    category: 'sovereign',
    tier: 'strategic',
    icon: 'AlertTriangle',
    color: 'yellow',
    inputs: [{ id: 'system', name: 'System Model', type: 'data' }],
    outputs: [{ id: 'failures', name: 'Failure Scenarios', type: 'data' }, { id: 'resilience', name: 'Resilience Score', type: 'score' }],
    configSchema: [{ key: 'intensity', label: 'Stress Intensity', type: 'select', defaultValue: 'medium', options: [{ label: 'Low', value: 'low' }, { label: 'Medium', value: 'medium' }, { label: 'High', value: 'high' }, { label: 'Catastrophic', value: 'catastrophic' }] }],
  },
  {
    id: 'sgas',
    name: 'SGAS™',
    shortName: 'SGAS',
    description: 'Synthetic Governance Agent System — autonomous governance agents for continuous oversight',
    category: 'sovereign',
    tier: 'strategic',
    icon: 'Building2',
    color: 'yellow',
    inputs: [{ id: 'policy', name: 'Governance Policy', type: 'data' }],
    outputs: [{ id: 'agents', name: 'Active Agents', type: 'data' }, { id: 'report', name: 'Governance Report', type: 'report' }],
    configSchema: [],
  },
  {
    id: 'eternal',
    name: 'CendiaEternal™',
    shortName: 'Eternal',
    description: 'Infinite decision persistence — decisions that outlast any single system or organization',
    category: 'sovereign',
    tier: 'strategic',
    icon: 'Infinity',
    color: 'yellow',
    inputs: [{ id: 'decision', name: 'Decision', type: 'decision' }],
    outputs: [{ id: 'eternalRecord', name: 'Eternal Record', type: 'evidence' }],
    configSchema: [],
  },
  {
    id: 'symbiont',
    name: 'CendiaSymbiont™',
    shortName: 'Symbiont',
    description: 'Human-AI symbiotic decision making — adaptive co-piloting with learning feedback',
    category: 'sovereign',
    tier: 'strategic',
    icon: 'Dna',
    color: 'yellow',
    inputs: [{ id: 'context', name: 'Decision Context', type: 'data' }],
    outputs: [{ id: 'recommendation', name: 'Co-Pilot Recommendation', type: 'decision' }],
    configSchema: [],
  },
  {
    id: 'shadow-ops',
    name: 'Shadow Operations',
    shortName: 'ShadowOps',
    description: 'Covert decision simulation — run shadow decisions in parallel without affecting production',
    category: 'sovereign',
    tier: 'strategic',
    icon: 'Ghost',
    color: 'yellow',
    inputs: [{ id: 'decision', name: 'Decision', type: 'decision' }],
    outputs: [{ id: 'shadowResult', name: 'Shadow Result', type: 'data' }, { id: 'divergence', name: 'Divergence Report', type: 'report' }],
    configSchema: [],
  },
  {
    id: 'succession',
    name: 'CendiaSuccession™',
    shortName: 'Succession',
    description: 'AI model succession planning — seamless model transitions with zero decision drift',
    category: 'sovereign',
    tier: 'strategic',
    icon: 'ArrowRightCircle',
    color: 'yellow',
    inputs: [{ id: 'currentModel', name: 'Current Model', type: 'data' }, { id: 'candidateModel', name: 'Candidate Model', type: 'data' }],
    outputs: [{ id: 'comparison', name: 'Model Comparison', type: 'report' }, { id: 'driftScore', name: 'Drift Score', type: 'score' }],
    configSchema: [],
  },
  {
    id: 'sanctuary',
    name: 'CendiaSanctuary™',
    shortName: 'Sanctuary',
    description: 'Air-gapped sovereign deployment — complete data isolation and residency enforcement',
    category: 'sovereign',
    tier: 'strategic',
    icon: 'Lock',
    color: 'yellow',
    inputs: [],
    outputs: [{ id: 'status', name: 'Sanctuary Status', type: 'data' }],
    configSchema: [{ key: 'region', label: 'Data Residency Region', type: 'select', defaultValue: 'eu', options: [{ label: 'EU', value: 'eu' }, { label: 'US', value: 'us' }, { label: 'UK', value: 'uk' }, { label: 'APAC', value: 'apac' }] }],
  },
];

// =============================================================================
// HELPERS
// =============================================================================

export const getServiceById = (id: string): ServiceDefinition | undefined =>
  SERVICE_REGISTRY.find(s => s.id === id);

export const getServicesByCategory = (category: ServiceCategory): ServiceDefinition[] =>
  SERVICE_REGISTRY.filter(s => s.category === category);

export const getServicesByTier = (tier: ServiceTier): ServiceDefinition[] =>
  SERVICE_REGISTRY.filter(s => s.tier === tier);

export const getCategories = (): { id: ServiceCategory; label: string; color: string }[] => {
  const cats = new Map<ServiceCategory, { label: string; color: string }>();
  for (const s of SERVICE_REGISTRY) {
    if (!cats.has(s.category)) {
      const label = s.category.charAt(0).toUpperCase() + s.category.slice(1);
      cats.set(s.category, { label, color: s.color });
    }
  }
  return Array.from(cats.entries()).map(([id, v]) => ({ id, ...v }));
};

export const SERVICE_COUNT = SERVICE_REGISTRY.length;
