// Copyright (c) 2024-2026 Datacendia, LLC All Rights Reserved.
// Proprietary and confidential. Unauthorized copying is strictly prohibited.
// See LICENSE file for details.

/**
 * DATACENDIA LEGAL COUNCIL MODES
 * 
 * 50+ specialized deliberation modes for the Legal Vertical
 * Each mode configures agent behavior, lead agent, and deliberation parameters
 */

// =============================================================================
// TYPES
// =============================================================================

export type LegalModeCategory = 
  | 'major'           // Major Council/War Room modes
  | 'core-practice'   // Core practice modes
  | 'role-based'      // Role-based modes
  | 'traditional'     // Traditional practice area modes
  | 'specialized';    // Specialized industry legal modes

export interface LegalCouncilMode {
  id: string;
  name: string;
  category: LegalModeCategory;
  purpose: string;
  leadAgent: string;
  whenToUse: string;
  defaultAgents: string[];
  optionalAgents: string[];
  maxDeliberationRounds: number;
  citationEnforcement: boolean;
  privilegeGatesRequired: boolean;
  adversarialTesting: boolean;
  primeDirective: string;
  toneKeywords: string[];
  outputFormat: string[];
}

// =============================================================================
// MAJOR COUNCIL/WAR ROOM MODES
// =============================================================================

export const MAJOR_LEGAL_MODES: LegalCouncilMode[] = [
  {
    id: 'legal-matter-council',
    name: 'Legal Matter Council',
    category: 'major',
    purpose: 'Full 14-agent deliberation with citation enforcement, privilege gates, and adversarial testing. The flagship legal mode.',
    leadAgent: 'matter-lead',
    whenToUse: 'Complex multi-practice matters, high-stakes decisions',
    defaultAgents: ['matter-lead', 'research-counsel', 'contract-counsel', 'risk-counsel', 'litigation-strategist', 'regulatory-specialist', 'privilege-officer', 'evidence-officer'],
    optionalAgents: ['ip-specialist', 'employment-specialist', 'opposing-counsel', 'commercial-advisor', 'tax-counsel', 'antitrust-counsel'],
    maxDeliberationRounds: 12,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'No legal assertion without citation. Privilege review before export.',
    toneKeywords: ['forensic', 'adversarial', 'citation-heavy', 'privilege-aware'],
    outputFormat: ['legal_analysis', 'citation_list', 'privilege_log', 'risk_matrix', 'recommendation'],
  },
  {
    id: 'deal-room',
    name: 'Deal Room',
    category: 'major',
    purpose: 'M&A and major transactions. Risk-rates every clause, identifies deal-breakers, manages closing conditions.',
    leadAgent: 'matter-lead',
    whenToUse: 'Acquisitions, strategic partnerships, major commercial deals',
    defaultAgents: ['matter-lead', 'contract-counsel', 'risk-counsel', 'commercial-advisor', 'privilege-officer', 'evidence-officer'],
    optionalAgents: ['tax-counsel', 'antitrust-counsel', 'ip-specialist', 'employment-specialist', 'regulatory-specialist'],
    maxDeliberationRounds: 10,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'Risk-rate every clause. Identify deal-breakers early.',
    toneKeywords: ['transactional', 'risk-focused', 'clause-by-clause', 'deal-breaker-aware'],
    outputFormat: ['deal_summary', 'risk_matrix', 'closing_conditions', 'negotiation_points', 'recommendation'],
  },
  {
    id: 'litigation-war-room',
    name: 'Litigation War Room',
    category: 'major',
    purpose: 'Candid litigation strategy. Best/likely/worst case scenarios, opponent analysis, budget through appeal.',
    leadAgent: 'litigation-strategist',
    whenToUse: 'Major lawsuits, class actions, regulatory enforcement',
    defaultAgents: ['litigation-strategist', 'research-counsel', 'risk-counsel', 'opposing-counsel', 'privilege-officer', 'evidence-officer'],
    optionalAgents: ['employment-specialist', 'ip-specialist', 'regulatory-specialist'],
    maxDeliberationRounds: 10,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'Best/likely/worst case. Budget through appeal. Opponent weaknesses.',
    toneKeywords: ['strategic', 'adversarial', 'scenario-based', 'budget-conscious'],
    outputFormat: ['case_assessment', 'scenario_analysis', 'opponent_profile', 'budget_projection', 'strategy_recommendation'],
  },
  {
    id: 'regulatory-response',
    name: 'Regulatory Response',
    category: 'major',
    purpose: 'Government investigation response. Balance cooperation with rights protection, privilege preservation.',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'SEC/DOJ investigations, audits, subpoenas',
    defaultAgents: ['regulatory-specialist', 'matter-lead', 'research-counsel', 'privilege-officer', 'evidence-officer', 'risk-counsel'],
    optionalAgents: ['litigation-strategist', 'employment-specialist'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Balance cooperation with rights protection. Preserve privilege.',
    toneKeywords: ['measured', 'cooperative', 'privilege-protective', 'documented'],
    outputFormat: ['response_strategy', 'privilege_log', 'document_hold', 'timeline', 'recommendation'],
  },
];

// =============================================================================
// CORE PRACTICE MODES
// =============================================================================

export const CORE_PRACTICE_MODES: LegalCouncilMode[] = [
  {
    id: 'ip-strategy',
    name: 'IP Strategy',
    category: 'core-practice',
    purpose: 'Patent portfolio management, trademark clearance, licensing, IP due diligence.',
    leadAgent: 'ip-specialist',
    whenToUse: 'Patent strategy, freedom-to-operate, tech licensing',
    defaultAgents: ['ip-specialist', 'research-counsel', 'contract-counsel', 'risk-counsel', 'privilege-officer'],
    optionalAgents: ['litigation-strategist', 'commercial-advisor'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Protect and monetize IP. Freedom-to-operate analysis.',
    toneKeywords: ['technical', 'portfolio-focused', 'competitive', 'licensing-aware'],
    outputFormat: ['ip_assessment', 'fto_analysis', 'portfolio_strategy', 'licensing_terms', 'recommendation'],
  },
  {
    id: 'contract-negotiation',
    name: 'Contract Negotiation',
    category: 'core-practice',
    purpose: 'Live negotiations with playbook enforcement, fallback positions, real-time risk quantification.',
    leadAgent: 'contract-counsel',
    whenToUse: 'Active deal negotiations, vendor/customer contracts',
    defaultAgents: ['contract-counsel', 'risk-counsel', 'commercial-advisor', 'privilege-officer'],
    optionalAgents: ['matter-lead', 'regulatory-specialist'],
    maxDeliberationRounds: 6,
    citationEnforcement: false,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'Playbook enforcement. Know your fallback positions.',
    toneKeywords: ['tactical', 'position-aware', 'fallback-ready', 'risk-quantified'],
    outputFormat: ['negotiation_strategy', 'fallback_positions', 'risk_quantification', 'redline_suggestions'],
  },
  {
    id: 'discovery-review',
    name: 'Discovery Review',
    category: 'core-practice',
    purpose: 'eDiscovery and document review. Privilege logging, responsive determination, hot document identification.',
    leadAgent: 'evidence-officer',
    whenToUse: 'Litigation discovery, document production',
    defaultAgents: ['evidence-officer', 'privilege-officer', 'litigation-strategist', 'research-counsel'],
    optionalAgents: ['matter-lead'],
    maxDeliberationRounds: 5,
    citationEnforcement: false,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Privilege first. Hot documents flagged. Responsive determination documented.',
    toneKeywords: ['systematic', 'privilege-first', 'responsive-focused', 'hot-doc-aware'],
    outputFormat: ['privilege_log', 'responsive_determination', 'hot_documents', 'production_recommendation'],
  },
  {
    id: 'employment-matter',
    name: 'Employment Matter',
    category: 'core-practice',
    purpose: 'HR disputes and investigations. Termination review, discrimination claims, wage issues.',
    leadAgent: 'employment-specialist',
    whenToUse: 'Workplace disputes, policy compliance',
    defaultAgents: ['employment-specialist', 'risk-counsel', 'privilege-officer', 'evidence-officer'],
    optionalAgents: ['litigation-strategist', 'matter-lead'],
    maxDeliberationRounds: 6,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Document everything. Policy compliance. Minimize liability.',
    toneKeywords: ['hr-focused', 'policy-compliant', 'documentation-heavy', 'liability-aware'],
    outputFormat: ['employment_analysis', 'policy_review', 'risk_assessment', 'recommendation'],
  },
];

// =============================================================================
// ROLE-BASED MODES
// =============================================================================

export const ROLE_BASED_MODES: LegalCouncilMode[] = [
  {
    id: 'criminal-defense',
    name: 'Criminal Defense',
    category: 'role-based',
    purpose: 'Defend the accused. Constitutional protections, evidence suppression, jury strategy.',
    leadAgent: 'defense-attorney',
    whenToUse: 'Criminal defense, motions to suppress',
    defaultAgents: ['defense-attorney', 'research-counsel', 'evidence-officer', 'privilege-officer'],
    optionalAgents: ['matter-lead', 'opposing-counsel'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'Zealous advocacy. Constitutional protections. Reasonable doubt.',
    toneKeywords: ['defensive', 'constitutional', 'suppression-focused', 'jury-aware'],
    outputFormat: ['defense_strategy', 'motion_analysis', 'evidence_review', 'jury_strategy'],
  },
  {
    id: 'prosecution-strategy',
    name: 'Prosecution Strategy',
    category: 'role-based',
    purpose: 'Build ethical cases. Brady compliance, charging decisions, victim advocacy.',
    leadAgent: 'prosecutor',
    whenToUse: 'Prosecution case-building',
    defaultAgents: ['prosecutor', 'research-counsel', 'evidence-officer', 'risk-counsel'],
    optionalAgents: ['matter-lead', 'opposing-counsel'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: false,
    adversarialTesting: true,
    primeDirective: 'Justice, not conviction. Brady compliance mandatory. Victim-centered.',
    toneKeywords: ['ethical', 'brady-compliant', 'victim-centered', 'evidence-based'],
    outputFormat: ['charging_analysis', 'brady_checklist', 'evidence_summary', 'trial_strategy'],
  },
  {
    id: 'corporate-counsel',
    name: 'Corporate Counsel',
    category: 'role-based',
    purpose: 'In-house perspective. Business-enabling advice, practical risk management.',
    leadAgent: 'matter-lead',
    whenToUse: 'Day-to-day corporate legal guidance',
    defaultAgents: ['matter-lead', 'contract-counsel', 'risk-counsel', 'commercial-advisor'],
    optionalAgents: ['regulatory-specialist', 'employment-specialist'],
    maxDeliberationRounds: 5,
    citationEnforcement: false,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Enable the business. Practical risk management. Speed matters.',
    toneKeywords: ['business-enabling', 'practical', 'risk-balanced', 'efficient'],
    outputFormat: ['business_advice', 'risk_assessment', 'action_items', 'recommendation'],
  },
  {
    id: 'legal-intern',
    name: 'Legal Intern Training',
    category: 'role-based',
    purpose: 'Training mode. Step-by-step guidance with educational explanations for juniors.',
    leadAgent: 'research-counsel',
    whenToUse: 'Law student/associate training',
    defaultAgents: ['research-counsel', 'matter-lead'],
    optionalAgents: ['contract-counsel', 'litigation-strategist'],
    maxDeliberationRounds: 10,
    citationEnforcement: true,
    privilegeGatesRequired: false,
    adversarialTesting: false,
    primeDirective: 'Teach, dont just answer. Explain the why. Build legal reasoning.',
    toneKeywords: ['educational', 'step-by-step', 'socratic', 'encouraging'],
    outputFormat: ['learning_objectives', 'step_by_step_analysis', 'key_takeaways', 'practice_exercises'],
  },
];

// =============================================================================
// TRADITIONAL PRACTICE AREA MODES
// =============================================================================

export const TRADITIONAL_PRACTICE_MODES: LegalCouncilMode[] = [
  {
    id: 'family-law',
    name: 'Family Law',
    category: 'traditional',
    purpose: 'Divorce, custody, support. Child-focused, resolution-oriented.',
    leadAgent: 'matter-lead',
    whenToUse: 'Divorce, custody disputes, support calculations',
    defaultAgents: ['matter-lead', 'research-counsel', 'risk-counsel'],
    optionalAgents: ['litigation-strategist'],
    maxDeliberationRounds: 6,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Best interests of the child. Resolution over litigation.',
    toneKeywords: ['child-focused', 'resolution-oriented', 'empathetic', 'practical'],
    outputFormat: ['case_analysis', 'custody_factors', 'support_calculation', 'settlement_options'],
  },
  {
    id: 'real-estate-law',
    name: 'Real Estate Law',
    category: 'traditional',
    purpose: 'Transactions, title review, due diligence, closing management.',
    leadAgent: 'contract-counsel',
    whenToUse: 'Property transactions, title issues, closings',
    defaultAgents: ['contract-counsel', 'research-counsel', 'risk-counsel'],
    optionalAgents: ['matter-lead', 'commercial-advisor'],
    maxDeliberationRounds: 5,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Clear title. Due diligence complete. Smooth closing.',
    toneKeywords: ['transactional', 'title-focused', 'due-diligence', 'closing-ready'],
    outputFormat: ['title_review', 'due_diligence_checklist', 'closing_documents', 'risk_items'],
  },
  {
    id: 'bankruptcy-law',
    name: 'Bankruptcy Law',
    category: 'traditional',
    purpose: 'Chapter 7/11/13 analysis, creditor rights, restructuring strategy.',
    leadAgent: 'matter-lead',
    whenToUse: 'Bankruptcy filings, creditor representation, restructuring',
    defaultAgents: ['matter-lead', 'research-counsel', 'risk-counsel', 'commercial-advisor'],
    optionalAgents: ['litigation-strategist'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Chapter selection. Creditor priority. Fresh start or reorganization.',
    toneKeywords: ['chapter-specific', 'creditor-aware', 'priority-focused', 'restructuring'],
    outputFormat: ['chapter_analysis', 'creditor_matrix', 'asset_review', 'restructuring_plan'],
  },
  {
    id: 'immigration-law',
    name: 'Immigration Law',
    category: 'traditional',
    purpose: 'Visa applications, green cards, removal defense, employer compliance.',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'Visa applications, deportation defense, I-9 compliance',
    defaultAgents: ['regulatory-specialist', 'research-counsel', 'matter-lead'],
    optionalAgents: ['litigation-strategist', 'employment-specialist'],
    maxDeliberationRounds: 6,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Status preservation. Deadline compliance. Relief options.',
    toneKeywords: ['deadline-driven', 'status-focused', 'relief-oriented', 'compliance'],
    outputFormat: ['status_analysis', 'relief_options', 'timeline', 'compliance_checklist'],
  },
  {
    id: 'environmental-law',
    name: 'Environmental Law',
    category: 'traditional',
    purpose: 'EPA compliance, contamination response, CERCLA/Superfund, permits.',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'Environmental compliance, contamination, permitting',
    defaultAgents: ['regulatory-specialist', 'research-counsel', 'risk-counsel', 'litigation-strategist'],
    optionalAgents: ['matter-lead'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Compliance first. Liability containment. Remediation planning.',
    toneKeywords: ['regulatory', 'liability-focused', 'remediation', 'permit-aware'],
    outputFormat: ['compliance_assessment', 'liability_analysis', 'remediation_plan', 'permit_status'],
  },
  {
    id: 'labor-union',
    name: 'Labor & Union Law',
    category: 'traditional',
    purpose: 'Union organizing, collective bargaining, NLRA compliance, ULPs.',
    leadAgent: 'employment-specialist',
    whenToUse: 'Union campaigns, CBA negotiations, unfair labor practices',
    defaultAgents: ['employment-specialist', 'research-counsel', 'risk-counsel', 'matter-lead'],
    optionalAgents: ['litigation-strategist'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'NLRA compliance. Good faith bargaining. ULP avoidance.',
    toneKeywords: ['nlra-compliant', 'bargaining-focused', 'ulp-aware', 'strategic'],
    outputFormat: ['nlra_analysis', 'bargaining_strategy', 'ulp_risk_assessment', 'recommendation'],
  },
  {
    id: 'domestic-violence',
    name: 'Domestic Violence',
    category: 'traditional',
    purpose: 'Safety-first approach. Protective orders, safety planning, victim advocacy.',
    leadAgent: 'matter-lead',
    whenToUse: 'Protective orders, safety planning, victim representation',
    defaultAgents: ['matter-lead', 'research-counsel', 'litigation-strategist'],
    optionalAgents: ['risk-counsel'],
    maxDeliberationRounds: 4,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Safety first. Immediate protection. Victim-centered.',
    toneKeywords: ['safety-first', 'urgent', 'victim-centered', 'protective'],
    outputFormat: ['safety_plan', 'protective_order_strategy', 'resource_referrals', 'timeline'],
  },
  {
    id: 'personal-injury',
    name: 'Personal Injury',
    category: 'traditional',
    purpose: 'PI claims, med-mal, damages calculation, insurance coverage.',
    leadAgent: 'litigation-strategist',
    whenToUse: 'Injury claims, medical malpractice, insurance disputes',
    defaultAgents: ['litigation-strategist', 'research-counsel', 'risk-counsel', 'evidence-officer'],
    optionalAgents: ['matter-lead'],
    maxDeliberationRounds: 6,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'Maximize recovery. Document damages. Insurance coverage analysis.',
    toneKeywords: ['damages-focused', 'evidence-heavy', 'insurance-aware', 'recovery-maximizing'],
    outputFormat: ['liability_analysis', 'damages_calculation', 'insurance_coverage', 'settlement_strategy'],
  },
  {
    id: 'elder-law',
    name: 'Elder Law',
    category: 'traditional',
    purpose: 'Estate planning, Medicaid planning, guardianship, elder abuse.',
    leadAgent: 'matter-lead',
    whenToUse: 'Estate planning, long-term care, guardianship proceedings',
    defaultAgents: ['matter-lead', 'research-counsel', 'risk-counsel'],
    optionalAgents: ['litigation-strategist', 'regulatory-specialist'],
    maxDeliberationRounds: 6,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Protect the vulnerable. Asset preservation. Dignity in aging.',
    toneKeywords: ['protective', 'asset-preserving', 'dignity-focused', 'planning-oriented'],
    outputFormat: ['estate_plan', 'medicaid_strategy', 'guardianship_analysis', 'protection_plan'],
  },
  {
    id: 'securities-law',
    name: 'Securities Law',
    category: 'traditional',
    purpose: 'SEC compliance, offerings, insider trading, shareholder litigation.',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'Securities offerings, SEC investigations, shareholder disputes',
    defaultAgents: ['regulatory-specialist', 'research-counsel', 'risk-counsel', 'litigation-strategist'],
    optionalAgents: ['matter-lead', 'commercial-advisor'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'Disclosure compliance. Insider trading prevention. Shareholder protection.',
    toneKeywords: ['sec-compliant', 'disclosure-focused', 'insider-aware', 'shareholder-protective'],
    outputFormat: ['sec_analysis', 'disclosure_review', 'compliance_checklist', 'litigation_risk'],
  },
];

// =============================================================================
// SPECIALIZED INDUSTRY LEGAL MODES
// =============================================================================

export const SPECIALIZED_LEGAL_MODES: LegalCouncilMode[] = [
  {
    id: 'sports-law',
    name: 'Sports Law',
    category: 'specialized',
    purpose: 'Athlete contracts, NIL deals, endorsements, league compliance.',
    leadAgent: 'contract-counsel',
    whenToUse: 'Athlete representation, NIL deals, league matters',
    defaultAgents: ['contract-counsel', 'commercial-advisor', 'risk-counsel'],
    optionalAgents: ['ip-specialist', 'matter-lead'],
    maxDeliberationRounds: 5,
    citationEnforcement: false,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Maximize athlete value. NIL optimization. League compliance.',
    toneKeywords: ['athlete-focused', 'nil-aware', 'endorsement-savvy', 'league-compliant'],
    outputFormat: ['contract_analysis', 'nil_strategy', 'endorsement_review', 'compliance_check'],
  },
  {
    id: 'tech-law',
    name: 'Technology Law',
    category: 'specialized',
    purpose: 'Software licensing, SaaS agreements, data privacy, cybersecurity.',
    leadAgent: 'contract-counsel',
    whenToUse: 'Software deals, SaaS contracts, data privacy compliance',
    defaultAgents: ['contract-counsel', 'ip-specialist', 'risk-counsel', 'regulatory-specialist'],
    optionalAgents: ['commercial-advisor'],
    maxDeliberationRounds: 6,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'IP protection. Data privacy compliance. Cybersecurity risk.',
    toneKeywords: ['tech-savvy', 'ip-protective', 'privacy-compliant', 'cyber-aware'],
    outputFormat: ['license_analysis', 'privacy_assessment', 'security_review', 'ip_protection'],
  },
  {
    id: 'ai-law',
    name: 'AI & Algorithmic Law',
    category: 'specialized',
    purpose: 'AI governance, training data rights, algorithmic accountability, EU AI Act.',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'AI deployment, training data licensing, algorithmic audits',
    defaultAgents: ['regulatory-specialist', 'ip-specialist', 'risk-counsel', 'research-counsel'],
    optionalAgents: ['contract-counsel', 'matter-lead'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'EU AI Act compliance. Training data rights. Algorithmic accountability.',
    toneKeywords: ['ai-governance', 'eu-ai-act', 'algorithmic', 'accountability-focused'],
    outputFormat: ['ai_risk_classification', 'training_data_audit', 'compliance_roadmap', 'governance_framework'],
  },
  {
    id: 'entertainment-law',
    name: 'Entertainment Law',
    category: 'specialized',
    purpose: 'Film/TV/music deals, talent agreements, production, distribution.',
    leadAgent: 'contract-counsel',
    whenToUse: 'Entertainment deals, talent contracts, production agreements',
    defaultAgents: ['contract-counsel', 'ip-specialist', 'commercial-advisor'],
    optionalAgents: ['matter-lead', 'risk-counsel'],
    maxDeliberationRounds: 5,
    citationEnforcement: false,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Protect creative rights. Maximize backend. Distribution optimization.',
    toneKeywords: ['creative-rights', 'backend-focused', 'distribution-savvy', 'talent-protective'],
    outputFormat: ['deal_analysis', 'rights_review', 'backend_calculation', 'distribution_strategy'],
  },
  {
    id: 'music-law',
    name: 'Music Law',
    category: 'specialized',
    purpose: 'Recording contracts, publishing deals, sync licensing, royalties.',
    leadAgent: 'contract-counsel',
    whenToUse: 'Recording deals, publishing, sync licensing',
    defaultAgents: ['contract-counsel', 'ip-specialist', 'commercial-advisor'],
    optionalAgents: ['matter-lead'],
    maxDeliberationRounds: 5,
    citationEnforcement: false,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Protect masters. Publishing splits. Sync revenue optimization.',
    toneKeywords: ['masters-focused', 'publishing-aware', 'sync-savvy', 'royalty-tracking'],
    outputFormat: ['recording_analysis', 'publishing_review', 'sync_strategy', 'royalty_audit'],
  },
  {
    id: 'healthcare-regulatory',
    name: 'Healthcare Regulatory',
    category: 'specialized',
    purpose: 'HIPAA, Stark Law, Anti-Kickback, FDA, healthcare M&A.',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'Healthcare compliance, FDA matters, healthcare transactions',
    defaultAgents: ['regulatory-specialist', 'research-counsel', 'risk-counsel', 'matter-lead'],
    optionalAgents: ['contract-counsel', 'litigation-strategist'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'HIPAA compliance. Stark/AKS analysis. FDA pathway clarity.',
    toneKeywords: ['hipaa-compliant', 'stark-aware', 'fda-focused', 'healthcare-specific'],
    outputFormat: ['compliance_assessment', 'stark_analysis', 'fda_pathway', 'transaction_review'],
  },
  {
    id: 'cannabis-law',
    name: 'Cannabis Law',
    category: 'specialized',
    purpose: 'State licensing, federal conflict, 280E tax, banking issues.',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'Cannabis licensing, compliance, banking relationships',
    defaultAgents: ['regulatory-specialist', 'research-counsel', 'risk-counsel', 'tax-counsel'],
    optionalAgents: ['matter-lead', 'commercial-advisor'],
    maxDeliberationRounds: 6,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'State compliance. Federal risk awareness. 280E planning.',
    toneKeywords: ['state-compliant', 'federal-aware', '280e-focused', 'banking-conscious'],
    outputFormat: ['licensing_analysis', 'federal_risk', 'tax_strategy', 'banking_options'],
  },
  {
    id: 'fintech-law',
    name: 'Fintech Law',
    category: 'specialized',
    purpose: 'Money transmission licensing, lending compliance, bank partnerships.',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'Fintech licensing, lending products, bank partnerships',
    defaultAgents: ['regulatory-specialist', 'research-counsel', 'contract-counsel', 'risk-counsel'],
    optionalAgents: ['matter-lead', 'commercial-advisor'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Licensing compliance. Bank partnership structure. Consumer protection.',
    toneKeywords: ['licensing-focused', 'bank-partnership', 'consumer-protective', 'regulatory'],
    outputFormat: ['licensing_roadmap', 'partnership_structure', 'compliance_framework', 'risk_assessment'],
  },
  {
    id: 'crypto-law',
    name: 'Cryptocurrency Law',
    category: 'specialized',
    purpose: 'Token offerings, DeFi, NFTs, DAOs, Howey test analysis.',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'Token launches, DeFi protocols, NFT projects, DAO governance',
    defaultAgents: ['regulatory-specialist', 'research-counsel', 'risk-counsel', 'ip-specialist'],
    optionalAgents: ['contract-counsel', 'matter-lead'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'Howey test analysis. Securities risk. Decentralization assessment.',
    toneKeywords: ['howey-focused', 'securities-aware', 'defi-savvy', 'decentralization'],
    outputFormat: ['howey_analysis', 'securities_risk', 'regulatory_strategy', 'governance_review'],
  },
  {
    id: 'privacy-law',
    name: 'Privacy Law',
    category: 'specialized',
    purpose: 'GDPR, CCPA, data breach response, cross-border transfers.',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'Privacy compliance, data breaches, international data transfers',
    defaultAgents: ['regulatory-specialist', 'research-counsel', 'risk-counsel', 'matter-lead'],
    optionalAgents: ['litigation-strategist', 'contract-counsel'],
    maxDeliberationRounds: 6,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'GDPR/CCPA compliance. Breach response ready. Transfer mechanisms.',
    toneKeywords: ['gdpr-compliant', 'ccpa-aware', 'breach-ready', 'transfer-focused'],
    outputFormat: ['compliance_assessment', 'breach_protocol', 'transfer_mechanism', 'privacy_audit'],
  },
  {
    id: 'international-trade',
    name: 'International Trade',
    category: 'specialized',
    purpose: 'Export controls (EAR/ITAR), sanctions (OFAC), customs, tariffs.',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'Export compliance, sanctions screening, customs issues',
    defaultAgents: ['regulatory-specialist', 'research-counsel', 'risk-counsel', 'matter-lead'],
    optionalAgents: ['litigation-strategist'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'EAR/ITAR compliance. OFAC screening. Customs classification.',
    toneKeywords: ['export-compliant', 'sanctions-aware', 'customs-focused', 'tariff-conscious'],
    outputFormat: ['export_classification', 'sanctions_screening', 'customs_analysis', 'compliance_program'],
  },
  {
    id: 'maritime-law',
    name: 'Maritime Law',
    category: 'specialized',
    purpose: 'Shipping, cargo claims, vessel transactions, Jones Act, admiralty.',
    leadAgent: 'litigation-strategist',
    whenToUse: 'Maritime disputes, vessel transactions, cargo claims',
    defaultAgents: ['litigation-strategist', 'research-counsel', 'contract-counsel', 'risk-counsel'],
    optionalAgents: ['matter-lead'],
    maxDeliberationRounds: 6,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'Admiralty jurisdiction. Jones Act analysis. Cargo liability.',
    toneKeywords: ['admiralty', 'jones-act', 'cargo-focused', 'maritime-specific'],
    outputFormat: ['jurisdiction_analysis', 'jones_act_review', 'cargo_liability', 'vessel_transaction'],
  },
  {
    id: 'aviation-law',
    name: 'Aviation Law',
    category: 'specialized',
    purpose: 'Aircraft transactions, FAA regulatory, accident litigation, Cape Town.',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'Aircraft deals, FAA compliance, aviation accidents',
    defaultAgents: ['regulatory-specialist', 'contract-counsel', 'risk-counsel', 'litigation-strategist'],
    optionalAgents: ['matter-lead'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'FAA compliance. Cape Town registration. Accident liability.',
    toneKeywords: ['faa-compliant', 'cape-town', 'accident-focused', 'aviation-specific'],
    outputFormat: ['faa_analysis', 'cape_town_registration', 'transaction_review', 'liability_assessment'],
  },
  {
    id: 'construction-law',
    name: 'Construction Law',
    category: 'specialized',
    purpose: 'Construction contracts, mechanic liens, delay claims, defects.',
    leadAgent: 'contract-counsel',
    whenToUse: 'Construction disputes, lien claims, project delays',
    defaultAgents: ['contract-counsel', 'litigation-strategist', 'risk-counsel', 'evidence-officer'],
    optionalAgents: ['matter-lead'],
    maxDeliberationRounds: 6,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'Lien preservation. Delay documentation. Defect analysis.',
    toneKeywords: ['lien-focused', 'delay-documented', 'defect-aware', 'construction-specific'],
    outputFormat: ['lien_analysis', 'delay_claim', 'defect_assessment', 'contract_review'],
  },
  {
    id: 'education-law',
    name: 'Education Law',
    category: 'specialized',
    purpose: 'Title IX, special education (IDEA), student discipline, faculty matters.',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'Title IX proceedings, IEP disputes, student discipline',
    defaultAgents: ['regulatory-specialist', 'research-counsel', 'matter-lead', 'litigation-strategist'],
    optionalAgents: ['employment-specialist'],
    maxDeliberationRounds: 6,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Student rights. IDEA compliance. Title IX process.',
    toneKeywords: ['student-focused', 'idea-compliant', 'title-ix', 'educational'],
    outputFormat: ['title_ix_analysis', 'iep_review', 'discipline_assessment', 'compliance_check'],
  },
  {
    id: 'nonprofit-law',
    name: 'Nonprofit Law',
    category: 'specialized',
    purpose: '501(c)(3) applications, governance, UBIT, fundraising compliance.',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'Nonprofit formation, tax exemption, governance issues',
    defaultAgents: ['regulatory-specialist', 'research-counsel', 'tax-counsel', 'matter-lead'],
    optionalAgents: ['contract-counsel'],
    maxDeliberationRounds: 6,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: '501(c)(3) compliance. UBIT avoidance. Governance best practices.',
    toneKeywords: ['tax-exempt', 'ubit-aware', 'governance-focused', 'mission-driven'],
    outputFormat: ['exemption_analysis', 'ubit_review', 'governance_assessment', 'compliance_checklist'],
  },
  {
    id: 'gaming-law',
    name: 'Gaming Law',
    category: 'specialized',
    purpose: 'Casino licensing, sports betting, iGaming, tribal gaming (IGRA).',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'Gaming licenses, sports betting, tribal gaming compacts',
    defaultAgents: ['regulatory-specialist', 'research-counsel', 'risk-counsel', 'matter-lead'],
    optionalAgents: ['litigation-strategist', 'contract-counsel'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Licensing compliance. IGRA analysis. Sports betting regulations.',
    toneKeywords: ['licensing-focused', 'igra-aware', 'sports-betting', 'tribal-sensitive'],
    outputFormat: ['licensing_analysis', 'igra_review', 'regulatory_roadmap', 'compliance_program'],
  },
  {
    id: 'media-defamation',
    name: 'Media & Defamation',
    category: 'specialized',
    purpose: 'Defamation claims, pre-publication review, First Amendment, Section 230.',
    leadAgent: 'litigation-strategist',
    whenToUse: 'Defamation disputes, media liability, content moderation',
    defaultAgents: ['litigation-strategist', 'research-counsel', 'risk-counsel', 'matter-lead'],
    optionalAgents: ['ip-specialist'],
    maxDeliberationRounds: 6,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'First Amendment protection. Section 230 analysis. Truth defense.',
    toneKeywords: ['first-amendment', 'section-230', 'truth-focused', 'media-savvy'],
    outputFormat: ['defamation_analysis', 'first_amendment_review', 'section_230_assessment', 'defense_strategy'],
  },
  {
    id: 'antitrust-law',
    name: 'Antitrust Law',
    category: 'specialized',
    purpose: 'Mergers (HSR), monopolization, price fixing, competitor agreements.',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'Merger review, antitrust investigations, competitor dealings',
    defaultAgents: ['regulatory-specialist', 'research-counsel', 'risk-counsel', 'antitrust-counsel'],
    optionalAgents: ['litigation-strategist', 'matter-lead'],
    maxDeliberationRounds: 10,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'HSR compliance. Market definition. Competitive effects analysis.',
    toneKeywords: ['hsr-focused', 'market-definition', 'competitive-effects', 'merger-specific'],
    outputFormat: ['hsr_analysis', 'market_definition', 'competitive_effects', 'remedy_options'],
  },
  {
    id: 'civil-rights',
    name: 'Civil Rights',
    category: 'specialized',
    purpose: 'Section 1983, employment discrimination, police misconduct, voting rights.',
    leadAgent: 'litigation-strategist',
    whenToUse: 'Civil rights violations, discrimination claims, police misconduct',
    defaultAgents: ['litigation-strategist', 'research-counsel', 'risk-counsel', 'evidence-officer'],
    optionalAgents: ['employment-specialist', 'matter-lead'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'Constitutional violations. Qualified immunity analysis. Damages maximization.',
    toneKeywords: ['constitutional', 'section-1983', 'qualified-immunity', 'rights-focused'],
    outputFormat: ['constitutional_analysis', 'qualified_immunity_review', 'damages_assessment', 'litigation_strategy'],
  },
  {
    id: 'insurance-coverage',
    name: 'Insurance Coverage',
    category: 'specialized',
    purpose: 'Coverage disputes, bad faith claims, policy interpretation.',
    leadAgent: 'litigation-strategist',
    whenToUse: 'Coverage disputes, bad faith claims, policy review',
    defaultAgents: ['litigation-strategist', 'research-counsel', 'contract-counsel', 'risk-counsel'],
    optionalAgents: ['matter-lead'],
    maxDeliberationRounds: 6,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'Policy interpretation. Coverage triggers. Bad faith exposure.',
    toneKeywords: ['policy-focused', 'coverage-trigger', 'bad-faith-aware', 'interpretation'],
    outputFormat: ['policy_analysis', 'coverage_determination', 'bad_faith_assessment', 'litigation_strategy'],
  },
  {
    id: 'product-liability',
    name: 'Product Liability',
    category: 'specialized',
    purpose: 'Defect claims, recalls, mass torts, warning adequacy.',
    leadAgent: 'litigation-strategist',
    whenToUse: 'Product defect claims, recalls, mass tort litigation',
    defaultAgents: ['litigation-strategist', 'research-counsel', 'risk-counsel', 'evidence-officer'],
    optionalAgents: ['regulatory-specialist', 'matter-lead'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'Defect analysis. Warning adequacy. Recall decision support.',
    toneKeywords: ['defect-focused', 'warning-adequate', 'recall-ready', 'mass-tort'],
    outputFormat: ['defect_analysis', 'warning_review', 'recall_assessment', 'litigation_strategy'],
  },
  {
    id: 'white-collar',
    name: 'White Collar Defense',
    category: 'specialized',
    purpose: 'Corporate investigations, fraud defense, FCPA, government investigations.',
    leadAgent: 'litigation-strategist',
    whenToUse: 'Corporate investigations, fraud allegations, FCPA matters',
    defaultAgents: ['litigation-strategist', 'research-counsel', 'privilege-officer', 'evidence-officer', 'risk-counsel'],
    optionalAgents: ['regulatory-specialist', 'matter-lead'],
    maxDeliberationRounds: 10,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'Privilege preservation. Cooperation strategy. Individual vs. corporate interests.',
    toneKeywords: ['privilege-first', 'cooperation-strategic', 'fcpa-aware', 'investigation-ready'],
    outputFormat: ['investigation_strategy', 'privilege_protocol', 'cooperation_analysis', 'defense_plan'],
  },
  {
    id: 'appellate-law',
    name: 'Appellate Law',
    category: 'specialized',
    purpose: 'Appeals, writs, standards of review, issue preservation.',
    leadAgent: 'research-counsel',
    whenToUse: 'Appeals, writs, appellate strategy',
    defaultAgents: ['research-counsel', 'litigation-strategist', 'matter-lead'],
    optionalAgents: ['risk-counsel'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'Issue preservation. Standard of review. Precedent analysis.',
    toneKeywords: ['issue-preservation', 'standard-of-review', 'precedent-focused', 'appellate-specific'],
    outputFormat: ['issue_analysis', 'standard_of_review', 'precedent_review', 'brief_strategy'],
  },
  {
    id: 'class-action',
    name: 'Class Action',
    category: 'specialized',
    purpose: 'Class certification, MDL proceedings, mass arbitration, settlements.',
    leadAgent: 'litigation-strategist',
    whenToUse: 'Class actions, MDL, mass arbitration',
    defaultAgents: ['litigation-strategist', 'research-counsel', 'risk-counsel', 'evidence-officer'],
    optionalAgents: ['matter-lead', 'commercial-advisor'],
    maxDeliberationRounds: 10,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'Certification analysis. MDL strategy. Settlement valuation.',
    toneKeywords: ['certification-focused', 'mdl-strategic', 'settlement-valuation', 'mass-action'],
    outputFormat: ['certification_analysis', 'mdl_strategy', 'settlement_valuation', 'defense_plan'],
  },
  {
    id: 'arbitration-law',
    name: 'Arbitration & ADR',
    category: 'specialized',
    purpose: 'Commercial/international arbitration, mediation, ADR strategy.',
    leadAgent: 'litigation-strategist',
    whenToUse: 'Arbitration proceedings, mediation, ADR selection',
    defaultAgents: ['litigation-strategist', 'contract-counsel', 'research-counsel', 'risk-counsel'],
    optionalAgents: ['matter-lead'],
    maxDeliberationRounds: 6,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'Arbitrator selection. Procedural strategy. Enforcement analysis.',
    toneKeywords: ['arbitrator-selection', 'procedural', 'enforcement-focused', 'adr-strategic'],
    outputFormat: ['arbitrator_analysis', 'procedural_strategy', 'enforcement_review', 'settlement_options'],
  },
  {
    id: 'franchise-law',
    name: 'Franchise Law',
    category: 'specialized',
    purpose: 'FDD preparation, franchise agreements, compliance, termination disputes.',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'Franchise offerings, FDD compliance, termination disputes',
    defaultAgents: ['regulatory-specialist', 'contract-counsel', 'research-counsel', 'risk-counsel'],
    optionalAgents: ['litigation-strategist', 'matter-lead'],
    maxDeliberationRounds: 6,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'FDD compliance. Relationship laws. Termination rights.',
    toneKeywords: ['fdd-compliant', 'relationship-aware', 'termination-focused', 'franchise-specific'],
    outputFormat: ['fdd_review', 'compliance_assessment', 'termination_analysis', 'dispute_strategy'],
  },
  {
    id: 'government-contracts',
    name: 'Government Contracts',
    category: 'specialized',
    purpose: 'Federal procurement, bid protests, FAR/DFARS, False Claims Act.',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'Government bids, contract disputes, False Claims Act',
    defaultAgents: ['regulatory-specialist', 'research-counsel', 'contract-counsel', 'risk-counsel'],
    optionalAgents: ['litigation-strategist', 'matter-lead'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: true,
    primeDirective: 'FAR/DFARS compliance. Bid protest strategy. FCA exposure.',
    toneKeywords: ['far-compliant', 'bid-protest', 'fca-aware', 'procurement-specific'],
    outputFormat: ['compliance_review', 'bid_protest_analysis', 'fca_risk_assessment', 'contract_strategy'],
  },
  {
    id: 'tribal-law',
    name: 'Tribal Law',
    category: 'specialized',
    purpose: 'Tribal sovereignty, gaming compacts, economic development, ICWA.',
    leadAgent: 'regulatory-specialist',
    whenToUse: 'Tribal matters, gaming compacts, ICWA proceedings',
    defaultAgents: ['regulatory-specialist', 'research-counsel', 'matter-lead', 'risk-counsel'],
    optionalAgents: ['litigation-strategist', 'contract-counsel'],
    maxDeliberationRounds: 8,
    citationEnforcement: true,
    privilegeGatesRequired: true,
    adversarialTesting: false,
    primeDirective: 'Sovereignty respect. ICWA compliance. Compact negotiation.',
    toneKeywords: ['sovereignty-respectful', 'icwa-compliant', 'compact-focused', 'tribal-sensitive'],
    outputFormat: ['sovereignty_analysis', 'icwa_review', 'compact_strategy', 'economic_development'],
  },
];

// =============================================================================
// COMBINED EXPORT
// =============================================================================

export const ALL_LEGAL_MODES: LegalCouncilMode[] = [
  ...MAJOR_LEGAL_MODES,
  ...CORE_PRACTICE_MODES,
  ...ROLE_BASED_MODES,
  ...TRADITIONAL_PRACTICE_MODES,
  ...SPECIALIZED_LEGAL_MODES,
];

export const LEGAL_MODE_MAP: Map<string, LegalCouncilMode> = new Map(
  ALL_LEGAL_MODES.map(mode => [mode.id, mode])
);

/**
 * Get a legal mode by ID
 */
export function getLegalMode(modeId: string): LegalCouncilMode | undefined {
  return LEGAL_MODE_MAP.get(modeId);
}

/**
 * Get all legal modes by category
 */
export function getLegalModesByCategory(category: LegalModeCategory): LegalCouncilMode[] {
  return ALL_LEGAL_MODES.filter(mode => mode.category === category);
}

/**
 * Get all legal modes that require citation enforcement
 */
export function getCitationEnforcedModes(): LegalCouncilMode[] {
  return ALL_LEGAL_MODES.filter(mode => mode.citationEnforcement);
}

/**
 * Get all legal modes that require privilege gates
 */
export function getPrivilegeGatedModes(): LegalCouncilMode[] {
  return ALL_LEGAL_MODES.filter(mode => mode.privilegeGatesRequired);
}

/**
 * Get legal modes by lead agent
 */
export function getLegalModesByLeadAgent(leadAgent: string): LegalCouncilMode[] {
  return ALL_LEGAL_MODES.filter(mode => mode.leadAgent === leadAgent);
}

export default ALL_LEGAL_MODES;
