import { getLegalAgent } from './src/services/legal/LegalAgents';

// Get the agents for contract review
const contractCounsel = getLegalAgent('contract-counsel');
const riskCounsel = getLegalAgent('risk-counsel');
const commercialAdvisor = getLegalAgent('commercial-advisor');
const ipSpecialist = getLegalAgent('ip-specialist');
const matterLead = getLegalAgent('matter-lead');

console.log('═══════════════════════════════════════════════════════════════════════════');
console.log('                    DATACENDIA LEGAL VERTICAL');
console.log('                    Contract Review Deliberation');
console.log('═══════════════════════════════════════════════════════════════════════════');
console.log('');
console.log('CLIENT: DataFlow Analytics');
console.log('MATTER: CloudMatrix Enterprise Agreement Review');
console.log('CONTRACT VALUE: $2.4M (3-year term)');
console.log('URGENCY: CEO wants signed by Friday');
console.log('');
console.log('═══════════════════════════════════════════════════════════════════════════');
console.log('                         RED FLAGS IDENTIFIED');
console.log('═══════════════════════════════════════════════════════════════════════════');
console.log('');
console.log('  1. ⚠️  UNLIMITED LIABILITY for AUP breaches');
console.log('  2. ⚠️  UNILATERAL PRICING CHANGES with 30 days notice');
console.log('  3. ⚠️  NO SLA GUARANTEES - only "commercially reasonable efforts"');
console.log('  4. ⚠️  IP OWNERSHIP - vendor owns all derivative works from our data');
console.log('  5. ⚠️  ARBITRATION IN DELAWARE (we\'re in California)');
console.log('');

console.log('═══════════════════════════════════════════════════════════════════════════');
console.log('                      COUNCIL DELIBERATION');
console.log('═══════════════════════════════════════════════════════════════════════════');
console.log('');

console.log(`[${matterLead?.name} - ${matterLead?.role}]`);
console.log('');
console.log('Team, we have a $2.4M contract with significant red flags and a Friday deadline.');
console.log('Let\'s prioritize: which issues are deal-breakers vs. negotiable?');
console.log('Contract Counsel, start us off with the liability analysis.');
console.log('');
console.log('─────────────────────────────────────────────────────────────────────────────');
console.log('');

console.log(`[${contractCounsel?.name} - ${contractCounsel?.role}]`);
console.log('');
console.log('The UNLIMITED LIABILITY clause is the most dangerous provision in this contract.');
console.log('');
console.log('ANALYSIS:');
console.log('  • "Acceptable Use Policy" violations often include vague terms like');
console.log('    "excessive usage" or "harmful content" - easily triggered accidentally');
console.log('  • Unlimited liability means CloudMatrix could sue us for ANY amount');
console.log('  • With $2.4M contract value, our exposure should be CAPPED at contract value');
console.log('');
console.log('RECOMMENDATION:');
console.log('  • Demand mutual liability cap at 12 months of fees paid ($800K)');
console.log('  • Carve out only for: gross negligence, willful misconduct, IP infringement');
console.log('  • If they refuse ANY cap, this is a DEAL-BREAKER');
console.log('');
console.log('CITATION: See Limitation of Liability best practices per ABA Model Agreement §7.2');
console.log('');
console.log('─────────────────────────────────────────────────────────────────────────────');
console.log('');

console.log(`[${riskCounsel?.name} - ${riskCounsel?.role}]`);
console.log('');
console.log('I need to flag the PRICING CHANGE clause as a major financial risk.');
console.log('');
console.log('RISK ASSESSMENT:');
console.log('  • 30-day notice for price changes = they can double our costs mid-contract');
console.log('  • We\'re committing to 3 years, but they\'re not committing to pricing');
console.log('  • This creates UNQUANTIFIABLE budget exposure');
console.log('');
console.log('PROBABILITY: HIGH that they\'ll raise prices (SaaS vendors do this routinely)');
console.log('IMPACT: Could add $500K-$1M to total contract cost');
console.log('');
console.log('RECOMMENDATION:');
console.log('  • Lock pricing for full 3-year term, OR');
console.log('  • Cap annual increases at CPI + 3%, OR');
console.log('  • Add termination right if prices increase >10%');
console.log('');
console.log('─────────────────────────────────────────────────────────────────────────────');
console.log('');

console.log(`[${commercialAdvisor?.name} - ${commercialAdvisor?.role}]`);
console.log('');
console.log('From a business perspective, the NO SLA issue is critical.');
console.log('');
console.log('BUSINESS IMPACT:');
console.log('  • "Commercially reasonable efforts" is legally meaningless');
console.log('  • If their platform goes down, we have NO recourse');
console.log('  • This platform will process ALL our customer data - downtime = lost revenue');
console.log('');
console.log('WHAT WE NEED:');
console.log('  • 99.9% uptime SLA (allows ~8.7 hours downtime/year)');
console.log('  • Service credits for missed SLA (10% of monthly fee per 0.1% missed)');
console.log('  • Termination right if SLA missed 3 consecutive months');
console.log('');
console.log('NEGOTIATION LEVERAGE:');
console.log('  • $2.4M is significant - we\'re not a small customer');
console.log('  • Competitors (DataBricks, Snowflake) offer standard SLAs');
console.log('  • Mention we\'re evaluating alternatives if they won\'t commit');
console.log('');
console.log('─────────────────────────────────────────────────────────────────────────────');
console.log('');

console.log(`[${ipSpecialist?.name} - ${ipSpecialist?.role}]`);
console.log('');
console.log('The DERIVATIVE WORKS clause is a MAJOR IP TRAP.');
console.log('');
console.log('WHAT THIS MEANS:');
console.log('  • We feed our proprietary customer data into their AI platform');
console.log('  • Any insights, models, or analytics generated = THEY OWN IT');
console.log('  • They could sell insights derived from OUR data to our competitors');
console.log('');
console.log('THIS IS UNACCEPTABLE.');
console.log('');
console.log('REQUIRED CHANGES:');
console.log('  • Customer retains all rights to Customer Data and derivatives');
console.log('  • Vendor may only use aggregated, anonymized data for service improvement');
console.log('  • Explicit prohibition on sharing insights with third parties');
console.log('  • Data deletion within 30 days of termination');
console.log('');
console.log('CITATION: See GDPR Art. 17 (Right to Erasure), CCPA §1798.105');
console.log('');
console.log('─────────────────────────────────────────────────────────────────────────────');
console.log('');

console.log(`[${riskCounsel?.name} - ${riskCounsel?.role}]`);
console.log('');
console.log('On the DELAWARE ARBITRATION venue:');
console.log('');
console.log('RISK:');
console.log('  • We\'re California-based; Delaware arbitration = travel costs, inconvenience');
console.log('  • Delaware tends to be more business-friendly (pro-vendor)');
console.log('  • Arbitration itself limits our discovery rights');
console.log('');
console.log('RECOMMENDATION:');
console.log('  • Push for California venue (our home state)');
console.log('  • If they insist on arbitration, demand JAMS or AAA rules');
console.log('  • Add carve-out for injunctive relief in any court of competent jurisdiction');
console.log('');
console.log('PRIORITY: MEDIUM - this is negotiable, not a deal-breaker');
console.log('');
console.log('─────────────────────────────────────────────────────────────────────────────');
console.log('');

console.log(`[${matterLead?.name} - ${matterLead?.role}]`);
console.log('');
console.log('═══════════════════════════════════════════════════════════════════════════');
console.log('                    COUNCIL RECOMMENDATION SUMMARY');
console.log('═══════════════════════════════════════════════════════════════════════════');
console.log('');
console.log('DEAL-BREAKERS (Must Fix or Walk Away):');
console.log('  ❌ Unlimited liability → Cap at 12 months fees ($800K)');
console.log('  ❌ IP derivative ownership → Customer retains all data rights');
console.log('');
console.log('HIGH PRIORITY (Strong Push):');
console.log('  ⚠️  No SLA → Require 99.9% uptime with service credits');
console.log('  ⚠️  Pricing changes → Lock pricing or cap increases');
console.log('');
console.log('NEGOTIABLE (Nice to Have):');
console.log('  📝 Delaware arbitration → Push for California, accept if needed');
console.log('');
console.log('═══════════════════════════════════════════════════════════════════════════');
console.log('                    RECOMMENDED RESPONSE TO CEO');
console.log('═══════════════════════════════════════════════════════════════════════════');
console.log('');
console.log('"We cannot sign this contract by Friday in its current form.');
console.log('');
console.log('The unlimited liability and IP ownership clauses expose us to');
console.log('unquantifiable risk. I recommend we send CloudMatrix our redlines');
console.log('today and request a response by Wednesday.');
console.log('');
console.log('If they accept our core terms (liability cap + IP ownership), we can');
console.log('sign Thursday. If they refuse, we should evaluate DataBricks or');
console.log('Snowflake as alternatives.');
console.log('');
console.log('A 1-week delay is better than a $2.4M contract that could cost us');
console.log('millions more in liability or lost IP."');
console.log('');
console.log('═══════════════════════════════════════════════════════════════════════════');
console.log('                         REDLINE DOCUMENT');
console.log('═══════════════════════════════════════════════════════════════════════════');
console.log('');
console.log('Section 7.1 (Liability) - REDLINE:');
console.log('  CURRENT: "Customer shall have unlimited liability for any breach of');
console.log('            the Acceptable Use Policy."');
console.log('  PROPOSED: "Each party\'s total liability shall not exceed the fees paid');
console.log('             in the 12 months preceding the claim, except for gross');
console.log('             negligence, willful misconduct, or IP infringement."');
console.log('');
console.log('Section 4.3 (Pricing) - REDLINE:');
console.log('  CURRENT: "Vendor may modify pricing with 30 days written notice."');
console.log('  PROPOSED: "Pricing shall remain fixed for the Initial Term. Any renewal');
console.log('             pricing increases shall not exceed CPI + 3% annually."');
console.log('');
console.log('Section 9.2 (Intellectual Property) - REDLINE:');
console.log('  CURRENT: "Vendor owns all derivative works created from Customer Data."');
console.log('  PROPOSED: "Customer retains all rights to Customer Data and any insights,');
console.log('             models, or derivatives generated therefrom. Vendor may use');
console.log('             only aggregated, anonymized data for service improvement."');
console.log('');
console.log('Section 5.1 (Service Levels) - ADD:');
console.log('  "Vendor guarantees 99.9% platform availability. For each 0.1% below');
console.log('   the SLA, Customer receives a 10% credit on monthly fees. Customer');
console.log('   may terminate if SLA is missed for 3 consecutive months."');
console.log('');
console.log('Section 12.4 (Dispute Resolution) - REDLINE:');
console.log('  CURRENT: "Disputes shall be resolved by binding arbitration in Delaware."');
console.log('  PROPOSED: "Disputes shall be resolved by binding arbitration in');
console.log('             San Francisco, California under JAMS rules. Either party');
console.log('             may seek injunctive relief in any court of competent jurisdiction."');
console.log('');
console.log('═══════════════════════════════════════════════════════════════════════════');
console.log('                    CONFIDENCE: 92% | HUMAN SIGN-OFF: REQUIRED');
console.log('═══════════════════════════════════════════════════════════════════════════');
