/**
 * Compliance Frameworks - The Five Rings of Sovereignty
 * Complete mapping of all compliance domains across 8 pillars
 */

export type ComplianceDomain = 
  | 'ethical_ai'
  | 'cybersecurity'
  | 'privacy'
  | 'governance'
  | 'industry';

export type PillarId = 
  | 'helm' | 'lineage' | 'predict' | 'flow' 
  | 'health' | 'guard' | 'ethics' | 'agents';

export interface ComplianceFramework {
  id: string;
  code: string;
  name: string;
  fullName: string;
  domain: ComplianceDomain;
  description: string;
  version: string;
  jurisdiction: string[];
  industries: string[];
  pillars: PillarId[];
  controlCount: number;
  lastUpdated: Date;
  status: 'active' | 'deprecated' | 'draft';
}

// ============================================================================
// RING 1: ETHICAL AI FRAMEWORKS
// ============================================================================
export const ETHICAL_AI_FRAMEWORKS: ComplianceFramework[] = [
  {
    id: 'nist-ai-rmf',
    code: 'NIST-AI-RMF',
    name: 'NIST AI RMF',
    fullName: 'NIST Artificial Intelligence Risk Management Framework',
    domain: 'ethical_ai',
    description: 'Framework for managing AI risks throughout the AI lifecycle',
    version: '1.0',
    jurisdiction: ['US', 'Global'],
    industries: ['All'],
    pillars: ['helm', 'predict', 'ethics', 'agents'],
    controlCount: 72,
    lastUpdated: new Date('2023-01-26'),
    status: 'active',
  },
  {
    id: 'oecd-ai',
    code: 'OECD-AI',
    name: 'OECD AI Principles',
    fullName: 'OECD Principles on Artificial Intelligence',
    domain: 'ethical_ai',
    description: 'International standards for responsible stewardship of trustworthy AI',
    version: '2019',
    jurisdiction: ['OECD Countries', 'Global'],
    industries: ['All'],
    pillars: ['helm', 'predict', 'ethics', 'agents', 'lineage'],
    controlCount: 45,
    lastUpdated: new Date('2019-05-22'),
    status: 'active',
  },
  {
    id: 'unesco-ai',
    code: 'UNESCO-AI',
    name: 'UNESCO AI Ethics',
    fullName: 'UNESCO Recommendation on the Ethics of AI',
    domain: 'ethical_ai',
    description: 'Global standard for AI ethics covering all stages of the AI lifecycle',
    version: '2021',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['ethics', 'lineage', 'agents'],
    controlCount: 50,
    lastUpdated: new Date('2021-11-24'),
    status: 'active',
  },
  {
    id: 'iso-42001',
    code: 'ISO-42001',
    name: 'ISO 42001',
    fullName: 'ISO/IEC 42001 AI Management System',
    domain: 'ethical_ai',
    description: 'International standard for AI management systems',
    version: '2023',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['predict', 'ethics', 'agents', 'helm'],
    controlCount: 93,
    lastUpdated: new Date('2023-12-18'),
    status: 'active',
  },
  {
    id: 'eu-ai-act',
    code: 'EU-AI-ACT',
    name: 'EU AI Act',
    fullName: 'European Union Artificial Intelligence Act',
    domain: 'ethical_ai',
    description: 'Comprehensive AI regulation for the European Union',
    version: '2024',
    jurisdiction: ['EU'],
    industries: ['All'],
    pillars: ['ethics', 'agents', 'predict', 'guard'],
    controlCount: 85,
    lastUpdated: new Date('2024-03-13'),
    status: 'active',
  },
];

// ============================================================================
// RING 2: CYBERSECURITY FRAMEWORKS
// ============================================================================
export const CYBERSECURITY_FRAMEWORKS: ComplianceFramework[] = [
  {
    id: 'nist-800-53',
    code: 'NIST-800-53',
    name: 'NIST 800-53',
    fullName: 'NIST Special Publication 800-53 Security Controls',
    domain: 'cybersecurity',
    description: 'Comprehensive security and privacy controls catalog',
    version: 'Rev 5',
    jurisdiction: ['US', 'Global'],
    industries: ['All', 'Government'],
    pillars: ['guard', 'health', 'lineage', 'flow'],
    controlCount: 1189,
    lastUpdated: new Date('2020-09-23'),
    status: 'active',
  },
  {
    id: 'soc2',
    code: 'SOC2',
    name: 'SOC 2',
    fullName: 'Service Organization Control 2',
    domain: 'cybersecurity',
    description: 'Trust services criteria for security, availability, processing integrity',
    version: '2017',
    jurisdiction: ['US', 'Global'],
    industries: ['All', 'SaaS'],
    pillars: ['guard', 'helm', 'health', 'lineage'],
    controlCount: 64,
    lastUpdated: new Date('2017-01-01'),
    status: 'active',
  },
  {
    id: 'iso-27001',
    code: 'ISO-27001',
    name: 'ISO 27001',
    fullName: 'ISO/IEC 27001 Information Security Management',
    domain: 'cybersecurity',
    description: 'International standard for information security management systems',
    version: '2022',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['guard', 'lineage', 'health', 'flow'],
    controlCount: 93,
    lastUpdated: new Date('2022-10-25'),
    status: 'active',
  },
  {
    id: 'mitre-attack',
    code: 'MITRE-ATT&CK',
    name: 'MITRE ATT&CK',
    fullName: 'MITRE ATT&CK Framework',
    domain: 'cybersecurity',
    description: 'Knowledge base of adversary tactics and techniques',
    version: '14.1',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['guard', 'health', 'lineage'],
    controlCount: 201,
    lastUpdated: new Date('2023-10-31'),
    status: 'active',
  },
  {
    id: 'zero-trust',
    code: 'ZERO-TRUST',
    name: 'Zero Trust Architecture',
    fullName: 'NIST SP 800-207 Zero Trust Architecture',
    domain: 'cybersecurity',
    description: 'Security model based on strict access controls and continuous verification',
    version: '2020',
    jurisdiction: ['US', 'Global'],
    industries: ['All'],
    pillars: ['guard', 'flow', 'helm', 'agents'],
    controlCount: 35,
    lastUpdated: new Date('2020-08-11'),
    status: 'active',
  },
  {
    id: 'cmmc',
    code: 'CMMC',
    name: 'CMMC 2.0',
    fullName: 'Cybersecurity Maturity Model Certification',
    domain: 'cybersecurity',
    description: 'DoD cybersecurity requirements for defense contractors',
    version: '2.0',
    jurisdiction: ['US'],
    industries: ['Defense'],
    pillars: ['guard', 'lineage', 'flow'],
    controlCount: 110,
    lastUpdated: new Date('2021-11-04'),
    status: 'active',
  },
  {
    id: 'nist-800-137',
    code: 'NIST-800-137',
    name: 'NIST 800-137',
    fullName: 'NIST SP 800-137 Continuous Monitoring',
    domain: 'cybersecurity',
    description: 'Information security continuous monitoring for federal systems',
    version: '2011',
    jurisdiction: ['US'],
    industries: ['Government'],
    pillars: ['health', 'guard'],
    controlCount: 42,
    lastUpdated: new Date('2011-09-30'),
    status: 'active',
  },
  {
    id: 'cis-benchmarks',
    code: 'CIS',
    name: 'CIS Benchmarks',
    fullName: 'Center for Internet Security Benchmarks',
    domain: 'cybersecurity',
    description: 'Best practice security configuration guidelines',
    version: '8.0',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['guard', 'health'],
    controlCount: 153,
    lastUpdated: new Date('2023-03-15'),
    status: 'active',
  },
];

// ============================================================================
// RING 3: PRIVACY & DATA PROTECTION
// ============================================================================
export const PRIVACY_FRAMEWORKS: ComplianceFramework[] = [
  {
    id: 'gdpr',
    code: 'GDPR',
    name: 'GDPR',
    fullName: 'General Data Protection Regulation',
    domain: 'privacy',
    description: 'EU regulation on data protection and privacy',
    version: '2016/679',
    jurisdiction: ['EU', 'EEA'],
    industries: ['All'],
    pillars: ['lineage', 'guard', 'helm', 'ethics', 'flow'],
    controlCount: 99,
    lastUpdated: new Date('2018-05-25'),
    status: 'active',
  },
  {
    id: 'ccpa',
    code: 'CCPA/CPRA',
    name: 'CCPA/CPRA',
    fullName: 'California Consumer Privacy Act / California Privacy Rights Act',
    domain: 'privacy',
    description: 'California data privacy and protection law',
    version: '2023',
    jurisdiction: ['US-CA'],
    industries: ['All'],
    pillars: ['lineage', 'guard', 'ethics'],
    controlCount: 55,
    lastUpdated: new Date('2023-01-01'),
    status: 'active',
  },
  {
    id: 'hipaa',
    code: 'HIPAA',
    name: 'HIPAA',
    fullName: 'Health Insurance Portability and Accountability Act',
    domain: 'privacy',
    description: 'US law protecting sensitive patient health information',
    version: '2013 Omnibus',
    jurisdiction: ['US'],
    industries: ['Healthcare'],
    pillars: ['guard', 'lineage', 'health', 'predict'],
    controlCount: 75,
    lastUpdated: new Date('2013-01-25'),
    status: 'active',
  },
  {
    id: 'iso-27701',
    code: 'ISO-27701',
    name: 'ISO 27701',
    fullName: 'ISO/IEC 27701 Privacy Information Management',
    domain: 'privacy',
    description: 'Extension to ISO 27001 for privacy information management',
    version: '2019',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['guard', 'lineage', 'helm', 'flow'],
    controlCount: 49,
    lastUpdated: new Date('2019-08-06'),
    status: 'active',
  },
  {
    id: 'pci-dss',
    code: 'PCI-DSS',
    name: 'PCI DSS',
    fullName: 'Payment Card Industry Data Security Standard',
    domain: 'privacy',
    description: 'Security standards for card payment data protection',
    version: '4.0',
    jurisdiction: ['Global'],
    industries: ['Finance', 'Retail'],
    pillars: ['guard', 'lineage', 'flow'],
    controlCount: 64,
    lastUpdated: new Date('2022-03-31'),
    status: 'active',
  },
];

// ============================================================================
// RING 4: GOVERNANCE & AUDIT
// ============================================================================
export const GOVERNANCE_FRAMEWORKS: ComplianceFramework[] = [
  {
    id: 'coso-erm',
    code: 'COSO-ERM',
    name: 'COSO ERM',
    fullName: 'Committee of Sponsoring Organizations Enterprise Risk Management',
    domain: 'governance',
    description: 'Enterprise risk management framework',
    version: '2017',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['helm', 'predict', 'guard'],
    controlCount: 23,
    lastUpdated: new Date('2017-09-06'),
    status: 'active',
  },
  {
    id: 'cobit',
    code: 'COBIT',
    name: 'COBIT 2019',
    fullName: 'Control Objectives for Information Technologies',
    domain: 'governance',
    description: 'IT governance and management framework',
    version: '2019',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['helm', 'flow', 'guard', 'health'],
    controlCount: 40,
    lastUpdated: new Date('2018-11-18'),
    status: 'active',
  },
  {
    id: 'itil',
    code: 'ITIL',
    name: 'ITIL 4',
    fullName: 'Information Technology Infrastructure Library',
    domain: 'governance',
    description: 'IT service management best practices',
    version: '4.0',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['flow', 'health', 'helm'],
    controlCount: 34,
    lastUpdated: new Date('2019-02-18'),
    status: 'active',
  },
  {
    id: 'sox',
    code: 'SOX',
    name: 'SOX',
    fullName: 'Sarbanes-Oxley Act',
    domain: 'governance',
    description: 'US law for corporate financial accountability and auditing',
    version: '2002',
    jurisdiction: ['US'],
    industries: ['Public Companies', 'Finance'],
    pillars: ['helm', 'lineage', 'guard', 'flow'],
    controlCount: 66,
    lastUpdated: new Date('2002-07-30'),
    status: 'active',
  },
  {
    id: 'iso-9001',
    code: 'ISO-9001',
    name: 'ISO 9001',
    fullName: 'ISO 9001 Quality Management System',
    domain: 'governance',
    description: 'International standard for quality management systems',
    version: '2015',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['health', 'flow', 'helm'],
    controlCount: 51,
    lastUpdated: new Date('2015-09-23'),
    status: 'active',
  },
  {
    id: 'iso-20000',
    code: 'ISO-20000',
    name: 'ISO 20000',
    fullName: 'ISO/IEC 20000 IT Service Management',
    domain: 'governance',
    description: 'International standard for IT service management',
    version: '2018',
    jurisdiction: ['Global'],
    industries: ['All'],
    pillars: ['health', 'flow'],
    controlCount: 48,
    lastUpdated: new Date('2018-09-15'),
    status: 'active',
  },
];

// ============================================================================
// RING 5: INDUSTRY REGULATIONS
// ============================================================================
export const INDUSTRY_FRAMEWORKS: ComplianceFramework[] = [
  {
    id: 'basel-iii',
    code: 'BASEL-III',
    name: 'Basel III/IV',
    fullName: 'Basel III/IV Banking Supervision Framework',
    domain: 'industry',
    description: 'International regulatory framework for banks',
    version: 'III/IV',
    jurisdiction: ['Global'],
    industries: ['Banking', 'Finance'],
    pillars: ['helm', 'predict', 'guard'],
    controlCount: 87,
    lastUpdated: new Date('2023-01-01'),
    status: 'active',
  },
  {
    id: 'fedramp',
    code: 'FedRAMP',
    name: 'FedRAMP',
    fullName: 'Federal Risk and Authorization Management Program',
    domain: 'industry',
    description: 'US government cloud security authorization program',
    version: '2023',
    jurisdiction: ['US'],
    industries: ['Government'],
    pillars: ['guard', 'flow', 'health', 'lineage'],
    controlCount: 325,
    lastUpdated: new Date('2023-06-06'),
    status: 'active',
  },
  {
    id: 'gxp',
    code: 'GxP',
    name: 'GxP',
    fullName: 'Good Practice Guidelines (GLP, GMP, GCP, GDP)',
    domain: 'industry',
    description: 'Quality and safety guidelines for life sciences',
    version: 'Various',
    jurisdiction: ['Global'],
    industries: ['Pharma', 'Healthcare', 'Medical Devices'],
    pillars: ['flow', 'lineage', 'guard', 'ethics'],
    controlCount: 120,
    lastUpdated: new Date('2022-01-01'),
    status: 'active',
  },
  {
    id: 'nerc-cip',
    code: 'NERC-CIP',
    name: 'NERC CIP',
    fullName: 'North American Electric Reliability Corporation Critical Infrastructure Protection',
    domain: 'industry',
    description: 'Cybersecurity standards for bulk electric system',
    version: '2023',
    jurisdiction: ['US', 'Canada'],
    industries: ['Energy', 'Utilities'],
    pillars: ['guard', 'health', 'flow'],
    controlCount: 45,
    lastUpdated: new Date('2023-01-01'),
    status: 'active',
  },
  {
    id: 'cjis',
    code: 'CJIS',
    name: 'FBI CJIS',
    fullName: 'Criminal Justice Information Services Security Policy',
    domain: 'industry',
    description: 'Security policy for criminal justice information',
    version: '5.9.1',
    jurisdiction: ['US'],
    industries: ['Government', 'Law Enforcement'],
    pillars: ['guard', 'lineage', 'ethics'],
    controlCount: 52,
    lastUpdated: new Date('2022-06-01'),
    status: 'active',
  },
  {
    id: 'ifrs-9',
    code: 'IFRS-9',
    name: 'IFRS 9',
    fullName: 'International Financial Reporting Standard 9',
    domain: 'industry',
    description: 'Financial instruments accounting standard with ECL modeling',
    version: '2014',
    jurisdiction: ['Global'],
    industries: ['Finance', 'Banking'],
    pillars: ['predict', 'helm'],
    controlCount: 38,
    lastUpdated: new Date('2014-07-24'),
    status: 'active',
  },
  {
    id: 'sr-11-7',
    code: 'SR-11-7',
    name: 'SR 11-7',
    fullName: 'Federal Reserve Model Risk Management Guidance',
    domain: 'industry',
    description: 'Guidance on model risk management for banking',
    version: '2011',
    jurisdiction: ['US'],
    industries: ['Banking'],
    pillars: ['predict', 'ethics', 'guard'],
    controlCount: 28,
    lastUpdated: new Date('2011-04-04'),
    status: 'active',
  },
];

// ============================================================================
// ALL FRAMEWORKS COMBINED
// ============================================================================
export const ALL_FRAMEWORKS: ComplianceFramework[] = [
  ...ETHICAL_AI_FRAMEWORKS,
  ...CYBERSECURITY_FRAMEWORKS,
  ...PRIVACY_FRAMEWORKS,
  ...GOVERNANCE_FRAMEWORKS,
  ...INDUSTRY_FRAMEWORKS,
];

// ============================================================================
// PILLAR-TO-FRAMEWORK MAPPING
// ============================================================================
export const PILLAR_FRAMEWORK_MAPPING: Record<PillarId, Record<ComplianceDomain, string[]>> = {
  helm: {
    ethical_ai: ['NIST-AI-RMF', 'OECD-AI', 'ISO-42001'],
    cybersecurity: ['SOC2', 'ZERO-TRUST'],
    privacy: ['GDPR', 'ISO-27701'],
    governance: ['COSO-ERM', 'COBIT', 'SOX'],
    industry: ['BASEL-III', 'IFRS-9'],
  },
  lineage: {
    ethical_ai: ['UNESCO-AI', 'OECD-AI'],
    cybersecurity: ['NIST-800-53', 'MITRE-ATT&CK', 'ISO-27001'],
    privacy: ['GDPR', 'CCPA/CPRA', 'HIPAA', 'PCI-DSS'],
    governance: ['SOX', 'ISO-27001'],
    industry: ['HIPAA', 'PCI-DSS', 'FedRAMP'],
  },
  predict: {
    ethical_ai: ['OECD-AI', 'ISO-42001', 'EU-AI-ACT'],
    cybersecurity: ['NIST-AI-RMF'],
    privacy: ['GDPR', 'HIPAA'],
    governance: ['COSO-ERM', 'SR-11-7'],
    industry: ['BASEL-III', 'IFRS-9', 'SR-11-7'],
  },
  flow: {
    ethical_ai: ['ISO-42001'],
    cybersecurity: ['ZERO-TRUST', 'SOC2', 'NIST-800-53'],
    privacy: ['ISO-27701', 'GDPR'],
    governance: ['ITIL', 'COBIT'],
    industry: ['GxP', 'FedRAMP', 'NERC-CIP'],
  },
  health: {
    ethical_ai: ['ISO-42001'],
    cybersecurity: ['NIST-800-137', 'MITRE-ATT&CK', 'CIS'],
    privacy: ['HIPAA', 'GDPR'],
    governance: ['ISO-20000', 'ISO-9001', 'ITIL'],
    industry: ['NERC-CIP'],
  },
  guard: {
    ethical_ai: ['EU-AI-ACT'],
    cybersecurity: ['NIST-800-53', 'MITRE-ATT&CK', 'ZERO-TRUST', 'ISO-27001', 'SOC2', 'CMMC', 'CIS'],
    privacy: ['GDPR', 'ISO-27701', 'HIPAA', 'PCI-DSS'],
    governance: ['SOC2', 'COBIT'],
    industry: ['CJIS', 'CMMC', 'FedRAMP'],
  },
  ethics: {
    ethical_ai: ['NIST-AI-RMF', 'OECD-AI', 'UNESCO-AI', 'ISO-42001', 'EU-AI-ACT'],
    cybersecurity: ['NIST-800-53'],
    privacy: ['GDPR'],
    governance: ['COSO-ERM'],
    industry: ['GxP', 'CJIS'],
  },
  agents: {
    ethical_ai: ['OECD-AI', 'UNESCO-AI', 'ISO-42001', 'EU-AI-ACT', 'NIST-AI-RMF'],
    cybersecurity: ['NIST-AI-RMF', 'ZERO-TRUST'],
    privacy: ['GDPR'],
    governance: ['ISO-42001'],
    industry: ['SR-11-7'],
  },
};
