// @ts-nocheck
// =============================================================================
// TECH TEAM PANEL
// UI for monitoring and controlling the AI Tech Team
// =============================================================================
function stryNS_9fa48() {
  var g = typeof globalThis === 'object' && globalThis && globalThis.Math === Math && globalThis || new Function("return this")();
  var ns = g.__stryker__ || (g.__stryker__ = {});
  if (ns.activeMutant === undefined && g.process && g.process.env && g.process.env.__STRYKER_ACTIVE_MUTANT__) {
    ns.activeMutant = g.process.env.__STRYKER_ACTIVE_MUTANT__;
  }
  function retrieveNS() {
    return ns;
  }
  stryNS_9fa48 = retrieveNS;
  return retrieveNS();
}
stryNS_9fa48();
function stryCov_9fa48() {
  var ns = stryNS_9fa48();
  var cov = ns.mutantCoverage || (ns.mutantCoverage = {
    static: {},
    perTest: {}
  });
  function cover() {
    var c = cov.static;
    if (ns.currentTestId) {
      c = cov.perTest[ns.currentTestId] = cov.perTest[ns.currentTestId] || {};
    }
    var a = arguments;
    for (var i = 0; i < a.length; i++) {
      c[a[i]] = (c[a[i]] || 0) + 1;
    }
  }
  stryCov_9fa48 = cover;
  cover.apply(null, arguments);
}
function stryMutAct_9fa48(id) {
  var ns = stryNS_9fa48();
  function isActive(id) {
    if (ns.activeMutant === id) {
      if (ns.hitCount !== void 0 && ++ns.hitCount > ns.hitLimit) {
        throw new Error('Stryker: Hit count limit reached (' + ns.hitCount + ')');
      }
      return true;
    }
    return false;
  }
  stryMutAct_9fa48 = isActive;
  return isActive(id);
}
import React, { useState, useEffect, useCallback } from 'react';
import { Users, AlertTriangle, CheckCircle, Clock, Zap, Settings, Play, Pause, RefreshCw, ChevronDown, ChevronRight, Code, Bug, Shield, Database, Cpu, FileText, Brain, Rocket, Eye, Terminal, Loader2 } from 'lucide-react';
import { TECH_TEAM_AGENTS, TechTeamConfig, ErrorAnalysis, FixSuggestion } from '../../lib/agents/techTeam';
import { AutoHealService } from '../../services/AutoHealService';

// =============================================================================
// TECH TEAM DASHBOARD
// =============================================================================

export const TechTeamPanel: React.FC = () => {
  const [isExpanded, setIsExpanded] = useState(stryMutAct_9fa48("4245") ? true : (stryCov_9fa48("4245"), false));
  const [activeTab, setActiveTab] = useState<'team' | 'errors' | 'fixes' | 'settings'>('team');
  const [config, setConfig] = useState<TechTeamConfig>(AutoHealService.getConfig());
  const [errors, setErrors] = useState<ErrorAnalysis[]>(stryMutAct_9fa48("4247") ? ["Stryker was here"] : (stryCov_9fa48("4247"), []));
  const [fixes, setFixes] = useState<FixSuggestion[]>(stryMutAct_9fa48("4248") ? ["Stryker was here"] : (stryCov_9fa48("4248"), []));
  const [stats, setStats] = useState(AutoHealService.getStats());
  const [loadingFixes, setLoadingFixes] = useState<Set<string>>(new Set());
  const [notification, setNotification] = useState<string | null>(null);
  useEffect(() => {
    // Subscribe to errors
    const unsubscribe = AutoHealService.onError(error => {
      setErrors(AutoHealService.getErrorQueue());
      setStats(AutoHealService.getStats());
    });

    // Listen for fix-generated events
    const handleFixGenerated = (event: CustomEvent<FixSuggestion>) => {
      setFixes(AutoHealService.getFixHistory());
      setStats(AutoHealService.getStats());
      setNotification(`Fix generated by ${event.detail.agentCode}`);
      setTimeout(stryMutAct_9fa48("4253") ? () => undefined : (stryCov_9fa48("4253"), () => setNotification(null)), 3000);
      // Switch to fixes tab to show the new fix
      setActiveTab('fixes');
    };
    window.addEventListener('autoheal:fix-generated', handleFixGenerated as EventListener);

    // Initial load
    setErrors(AutoHealService.getErrorQueue());
    setFixes(AutoHealService.getFixHistory());

    // Poll for updates
    const interval = setInterval(() => {
      setErrors(AutoHealService.getErrorQueue());
      setFixes(AutoHealService.getFixHistory());
      setStats(AutoHealService.getStats());
    }, 2000);
    return () => {
      unsubscribe();
      clearInterval(interval);
      window.removeEventListener('autoheal:fix-generated', handleFixGenerated as EventListener);
    };
  }, stryMutAct_9fa48("4259") ? ["Stryker was here"] : (stryCov_9fa48("4259"), []));
  const handleConfigChange = (updates: Partial<TechTeamConfig>) => {
    AutoHealService.updateConfig(updates);
    setConfig(AutoHealService.getConfig());
  };

  // Handle requesting a fix with loading state
  const handleRequestFix = useCallback(async (errorId: string) => {
    if (stryMutAct_9fa48("4263") ? false : stryMutAct_9fa48("4262") ? true : (stryCov_9fa48("4262", "4263"), loadingFixes.has(errorId))) return; // Already loading

    setLoadingFixes(stryMutAct_9fa48("4264") ? () => undefined : (stryCov_9fa48("4264"), prev => new Set(prev).add(errorId)));
    setNotification('Generating fix...');
    try {
      const fix = await AutoHealService.requestFix(errorId);
      if (stryMutAct_9fa48("4269") ? false : stryMutAct_9fa48("4268") ? true : stryMutAct_9fa48("4267") ? fix : (stryCov_9fa48("4267", "4268", "4269"), !fix)) {
        setNotification('Failed to generate fix - check if Ollama is running');
        setTimeout(stryMutAct_9fa48("4272") ? () => undefined : (stryCov_9fa48("4272"), () => setNotification(null)), 3000);
      }
      // Success notification is handled by the event listener
    } catch (e) {
      console.error('[TechTeamPanel] Fix request failed:', e);
      setNotification('Fix request failed');
      setTimeout(stryMutAct_9fa48("4276") ? () => undefined : (stryCov_9fa48("4276"), () => setNotification(null)), 3000);
    } finally {
      setLoadingFixes(prev => {
        const next = new Set(prev);
        next.delete(errorId);
        return next;
      });
    }
  }, stryMutAct_9fa48("4279") ? [] : (stryCov_9fa48("4279"), [loadingFixes]));
  const getAgentIcon = (code: string) => {
    const icons: Record<string, React.ReactNode> = stryMutAct_9fa48("4281") ? {} : (stryCov_9fa48("4281"), {
      'dev-lead': <Users size={16} />,
      'frontend': <Code size={16} />,
      'backend': <Database size={16} />,
      'fullstack': <RefreshCw size={16} />,
      'devops': <Rocket size={16} />,
      'sre': <AlertTriangle size={16} />,
      'dba': <Database size={16} />,
      'qa-lead': <Eye size={16} />,
      'test-auto': <Bug size={16} />,
      'security-eng': <Shield size={16} />,
      'ai-ml-eng': <Brain size={16} />,
      'perf-eng': <Zap size={16} />,
      'docs': <FileText size={16} />
    });
    return stryMutAct_9fa48("4284") ? icons[code] && <Cpu size={16} /> : stryMutAct_9fa48("4283") ? false : stryMutAct_9fa48("4282") ? true : (stryCov_9fa48("4282", "4283", "4284"), icons[code] || <Cpu size={16} />);
  };
  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'critical':
        if (stryMutAct_9fa48("4286")) {} else {
          stryCov_9fa48("4286");
          return 'bg-red-500';
        }
      case 'high':
        if (stryMutAct_9fa48("4289")) {} else {
          stryCov_9fa48("4289");
          return 'bg-orange-500';
        }
      case 'medium':
        if (stryMutAct_9fa48("4292")) {} else {
          stryCov_9fa48("4292");
          return 'bg-yellow-500';
        }
      case 'low':
        if (stryMutAct_9fa48("4295")) {} else {
          stryCov_9fa48("4295");
          return 'bg-blue-500';
        }
      default:
        if (stryMutAct_9fa48("4298")) {} else {
          stryCov_9fa48("4298");
          return 'bg-gray-500';
        }
    }
  };
  if (stryMutAct_9fa48("4302") ? false : stryMutAct_9fa48("4301") ? true : stryMutAct_9fa48("4300") ? isExpanded : (stryCov_9fa48("4300", "4301", "4302"), !isExpanded)) {
    return <button onClick={stryMutAct_9fa48("4304") ? () => undefined : (stryCov_9fa48("4304"), () => setIsExpanded(stryMutAct_9fa48("4305") ? false : (stryCov_9fa48("4305"), true)))} className="fixed bottom-4 left-4 z-50 flex items-center gap-2 px-4 py-2 bg-slate-800 text-white rounded-lg shadow-lg hover:bg-slate-700 transition-colors">
        <Terminal size={18} />
        <span className="font-medium">Tech Team</span>
        {stryMutAct_9fa48("4308") ? errors.length > 0 || <span className="flex items-center justify-center w-5 h-5 bg-red-500 rounded-full text-xs font-bold">
            {errors.length}
          </span> : stryMutAct_9fa48("4307") ? false : stryMutAct_9fa48("4306") ? true : (stryCov_9fa48("4306", "4307", "4308"), (stryMutAct_9fa48("4311") ? errors.length <= 0 : stryMutAct_9fa48("4310") ? errors.length >= 0 : stryMutAct_9fa48("4309") ? true : (stryCov_9fa48("4309", "4310", "4311"), errors.length > 0)) && <span className="flex items-center justify-center w-5 h-5 bg-red-500 rounded-full text-xs font-bold">
            {errors.length}
          </span>)}
      </button>;
  }
  return <div className="fixed bottom-4 left-4 z-50 w-[480px] max-h-[600px] bg-slate-900 rounded-xl shadow-2xl border border-slate-700 overflow-hidden flex flex-col">
      {/* Header */}
      <div className="px-4 py-3 bg-slate-800 border-b border-slate-700 flex items-center justify-between">
        <div className="flex items-center gap-3 group">
          <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-cyan-500 to-blue-600 flex items-center justify-center">
            <Terminal size={18} className="text-white" />
          </div>
          <div>
            <h3 className="font-semibold text-white">AI Tech Team</h3>
            <p className="text-xs text-slate-400">{TECH_TEAM_AGENTS.length} agents • Auto-heal {config.autoHealEnabled ? 'ON' : 'OFF'}</p>
            <p className="text-[10px] text-slate-500 hidden group-hover:block max-w-[280px]">
              Engineering agents that monitor, diagnose, and propose fixes across the Datacendia stack.
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={stryMutAct_9fa48("4314") ? () => undefined : (stryCov_9fa48("4314"), () => handleConfigChange(stryMutAct_9fa48("4315") ? {} : (stryCov_9fa48("4315"), {
          autoHealEnabled: stryMutAct_9fa48("4316") ? config.autoHealEnabled : (stryCov_9fa48("4316"), !config.autoHealEnabled)
        })))} className={`p-2 rounded-lg transition-colors ${config.autoHealEnabled ? 'bg-green-500/20 text-green-400' : 'bg-slate-700 text-slate-400'}`} title={config.autoHealEnabled ? 'Disable Auto-Heal' : 'Enable Auto-Heal'}>
            {config.autoHealEnabled ? <Play size={16} /> : <Pause size={16} />}
          </button>
          <button onClick={stryMutAct_9fa48("4322") ? () => undefined : (stryCov_9fa48("4322"), () => setIsExpanded(stryMutAct_9fa48("4323") ? true : (stryCov_9fa48("4323"), false)))} className="p-2 rounded-lg bg-slate-700 text-slate-400 hover:text-white transition-colors">
            <ChevronDown size={16} />
          </button>
        </div>
      </div>

      {/* Notification Toast */}
      {stryMutAct_9fa48("4326") ? notification || <div className="px-4 py-2 bg-cyan-500/20 border-b border-cyan-500/30 text-cyan-400 text-xs font-medium flex items-center gap-2">
          <Loader2 size={12} className={notification.includes('Generating') ? 'animate-spin' : 'hidden'} />
          <CheckCircle size={12} className={notification.includes('generated') ? '' : 'hidden'} />
          <AlertTriangle size={12} className={notification.includes('Failed') || notification.includes('failed') ? '' : 'hidden'} />
          {notification}
        </div> : stryMutAct_9fa48("4325") ? false : stryMutAct_9fa48("4324") ? true : (stryCov_9fa48("4324", "4325", "4326"), notification && <div className="px-4 py-2 bg-cyan-500/20 border-b border-cyan-500/30 text-cyan-400 text-xs font-medium flex items-center gap-2">
          <Loader2 size={12} className={notification.includes('Generating') ? 'animate-spin' : 'hidden'} />
          <CheckCircle size={12} className={notification.includes('generated') ? '' : 'hidden'} />
          <AlertTriangle size={12} className={(stryMutAct_9fa48("4335") ? notification.includes('Failed') && notification.includes('failed') : stryMutAct_9fa48("4334") ? false : stryMutAct_9fa48("4333") ? true : (stryCov_9fa48("4333", "4334", "4335"), notification.includes('Failed') || notification.includes('failed'))) ? '' : 'hidden'} />
          {notification}
        </div>)}

      {/* Stats Bar */}
      <div className="px-4 py-2 bg-slate-800/50 border-b border-slate-700/50 flex items-center gap-4 text-xs">
        <div className="flex items-center gap-1.5">
          <div className={`w-2 h-2 rounded-full ${(stryMutAct_9fa48("4343") ? stats.isProcessing && loadingFixes.size > 0 : stryMutAct_9fa48("4342") ? false : stryMutAct_9fa48("4341") ? true : (stryCov_9fa48("4341", "4342", "4343"), stats.isProcessing || (stryMutAct_9fa48("4346") ? loadingFixes.size <= 0 : stryMutAct_9fa48("4345") ? loadingFixes.size >= 0 : stryMutAct_9fa48("4344") ? false : (stryCov_9fa48("4344", "4345", "4346"), loadingFixes.size > 0)))) ? 'bg-green-500 animate-pulse' : 'bg-slate-500'}`} />
          <span className="text-slate-400">{(stryMutAct_9fa48("4351") ? stats.isProcessing && loadingFixes.size > 0 : stryMutAct_9fa48("4350") ? false : stryMutAct_9fa48("4349") ? true : (stryCov_9fa48("4349", "4350", "4351"), stats.isProcessing || (stryMutAct_9fa48("4354") ? loadingFixes.size <= 0 : stryMutAct_9fa48("4353") ? loadingFixes.size >= 0 : stryMutAct_9fa48("4352") ? false : (stryCov_9fa48("4352", "4353", "4354"), loadingFixes.size > 0)))) ? 'Processing' : 'Idle'}</span>
        </div>
        <div className="flex items-center gap-1.5 text-slate-400">
          <AlertTriangle size={12} />
          <span>{stats.errorsInQueue} in queue</span>
        </div>
        <div className="flex items-center gap-1.5 text-slate-400">
          <CheckCircle size={12} />
          <span>{stats.fixesApplied} fixed</span>
        </div>
        <div className="flex items-center gap-1.5 text-slate-400">
          <Clock size={12} />
          <span>{stats.fixesThisHour}/hr</span>
        </div>
      </div>

      {/* Tabs */}
      <div className="px-4 py-2 border-b border-slate-700/50 flex gap-1">
        {(['team', 'errors', 'fixes', 'settings'] as const).map(stryMutAct_9fa48("4357") ? () => undefined : (stryCov_9fa48("4357"), tab => <button key={tab} onClick={stryMutAct_9fa48("4358") ? () => undefined : (stryCov_9fa48("4358"), () => setActiveTab(tab))} className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${(stryMutAct_9fa48("4362") ? activeTab !== tab : stryMutAct_9fa48("4361") ? false : stryMutAct_9fa48("4360") ? true : (stryCov_9fa48("4360", "4361", "4362"), activeTab === tab)) ? 'bg-cyan-500/20 text-cyan-400' : 'text-slate-400 hover:text-white hover:bg-slate-700/50'}`}>
            {stryMutAct_9fa48("4365") ? tab.charAt(0).toUpperCase() - tab.slice(1) : (stryCov_9fa48("4365"), (stryMutAct_9fa48("4367") ? tab.toUpperCase() : stryMutAct_9fa48("4366") ? tab.charAt(0).toLowerCase() : (stryCov_9fa48("4366", "4367"), tab.charAt(0).toUpperCase())) + (stryMutAct_9fa48("4368") ? tab : (stryCov_9fa48("4368"), tab.slice(1))))}
            {stryMutAct_9fa48("4371") ? tab === 'errors' && errors.length > 0 || <span className="ml-1.5 px-1.5 py-0.5 bg-red-500 rounded text-xs text-white">
                {errors.length}
              </span> : stryMutAct_9fa48("4370") ? false : stryMutAct_9fa48("4369") ? true : (stryCov_9fa48("4369", "4370", "4371"), (stryMutAct_9fa48("4373") ? tab === 'errors' || errors.length > 0 : stryMutAct_9fa48("4372") ? true : (stryCov_9fa48("4372", "4373"), (stryMutAct_9fa48("4375") ? tab !== 'errors' : stryMutAct_9fa48("4374") ? true : (stryCov_9fa48("4374", "4375"), tab === 'errors')) && (stryMutAct_9fa48("4379") ? errors.length <= 0 : stryMutAct_9fa48("4378") ? errors.length >= 0 : stryMutAct_9fa48("4377") ? true : (stryCov_9fa48("4377", "4378", "4379"), errors.length > 0)))) && <span className="ml-1.5 px-1.5 py-0.5 bg-red-500 rounded text-xs text-white">
                {errors.length}
              </span>)}
          </button>))}
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-4">
        {stryMutAct_9fa48("4382") ? activeTab === 'team' || <div className="space-y-2">
            {TECH_TEAM_AGENTS.map(agent => <div key={agent.id} className="p-3 rounded-lg bg-slate-800/50 border border-slate-700/50 hover:bg-slate-800 transition-colors">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{
              backgroundColor: `${agent.color}20`,
              color: agent.color
            }}>
                    {getAgentIcon(agent.code)}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <span className="font-medium text-white text-sm">{agent.name}</span>
                      <span className="text-xs text-slate-500">{agent.code}</span>
                    </div>
                    <p className="text-xs text-slate-400 truncate">{agent.role}</p>
                  </div>
                  <div className="text-xs text-slate-500">{agent.model.split(':')[0]}</div>
                </div>
              </div>)}
          </div> : stryMutAct_9fa48("4381") ? false : stryMutAct_9fa48("4380") ? true : (stryCov_9fa48("4380", "4381", "4382"), (stryMutAct_9fa48("4384") ? activeTab !== 'team' : stryMutAct_9fa48("4383") ? true : (stryCov_9fa48("4383", "4384"), activeTab === 'team')) && <div className="space-y-2">
            {TECH_TEAM_AGENTS.map(stryMutAct_9fa48("4386") ? () => undefined : (stryCov_9fa48("4386"), agent => <div key={agent.id} className="p-3 rounded-lg bg-slate-800/50 border border-slate-700/50 hover:bg-slate-800 transition-colors">
                <div className="flex items-center gap-3">
                  <div className="w-8 h-8 rounded-lg flex items-center justify-center" style={stryMutAct_9fa48("4387") ? {} : (stryCov_9fa48("4387"), {
              backgroundColor: `${agent.color}20`,
              color: agent.color
            })}>
                    {getAgentIcon(agent.code)}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <span className="font-medium text-white text-sm">{agent.name}</span>
                      <span className="text-xs text-slate-500">{agent.code}</span>
                    </div>
                    <p className="text-xs text-slate-400 truncate">{agent.role}</p>
                  </div>
                  <div className="text-xs text-slate-500">{agent.model.split(':')[0]}</div>
                </div>
              </div>))}
          </div>)}

        {stryMutAct_9fa48("4392") ? activeTab === 'errors' || <div className="space-y-2">
            {errors.length === 0 ? <div className="text-center py-8 text-slate-400">
                <CheckCircle size={32} className="mx-auto mb-2 text-green-500" />
                <p>No errors in queue</p>
              </div> : errors.map(error => <div key={error.id} className="p-3 rounded-lg bg-slate-800/50 border border-slate-700/50">
                  <div className="flex items-start gap-3">
                    <div className={`w-2 h-2 rounded-full mt-1.5 ${getSeverityColor(error.severity)}`} />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm text-white font-medium truncate">{error.message.substring(0, 80)}</p>
                      <p className="text-xs text-slate-400 mt-1">{error.file}:{error.line}</p>
                      <div className="flex items-center gap-2 mt-2">
                        <span className="text-xs px-2 py-0.5 rounded bg-slate-700 text-slate-300">
                          {error.assignedAgent}
                        </span>
                        <span className="text-xs text-slate-500">
                          {new Date(error.timestamp).toLocaleTimeString()}
                        </span>
                      </div>
                    </div>
                    <button onClick={() => handleRequestFix(error.id)} disabled={loadingFixes.has(error.id)} className={`px-3 py-1.5 rounded text-xs font-medium transition-colors flex items-center gap-1.5 ${loadingFixes.has(error.id) ? 'bg-cyan-500/10 text-cyan-400/50 cursor-wait' : 'bg-cyan-500/20 text-cyan-400 hover:bg-cyan-500/30'}`}>
                      {loadingFixes.has(error.id) ? <>
                          <Loader2 size={12} className="animate-spin" />
                          Fixing...
                        </> : 'Fix'}
                    </button>
                  </div>
                </div>)}
          </div> : stryMutAct_9fa48("4391") ? false : stryMutAct_9fa48("4390") ? true : (stryCov_9fa48("4390", "4391", "4392"), (stryMutAct_9fa48("4394") ? activeTab !== 'errors' : stryMutAct_9fa48("4393") ? true : (stryCov_9fa48("4393", "4394"), activeTab === 'errors')) && <div className="space-y-2">
            {(stryMutAct_9fa48("4398") ? errors.length !== 0 : stryMutAct_9fa48("4397") ? false : stryMutAct_9fa48("4396") ? true : (stryCov_9fa48("4396", "4397", "4398"), errors.length === 0)) ? <div className="text-center py-8 text-slate-400">
                <CheckCircle size={32} className="mx-auto mb-2 text-green-500" />
                <p>No errors in queue</p>
              </div> : errors.map(stryMutAct_9fa48("4399") ? () => undefined : (stryCov_9fa48("4399"), error => <div key={error.id} className="p-3 rounded-lg bg-slate-800/50 border border-slate-700/50">
                  <div className="flex items-start gap-3">
                    <div className={`w-2 h-2 rounded-full mt-1.5 ${getSeverityColor(error.severity)}`} />
                    <div className="flex-1 min-w-0">
                      <p className="text-sm text-white font-medium truncate">{stryMutAct_9fa48("4401") ? error.message : (stryCov_9fa48("4401"), error.message.substring(0, 80))}</p>
                      <p className="text-xs text-slate-400 mt-1">{error.file}:{error.line}</p>
                      <div className="flex items-center gap-2 mt-2">
                        <span className="text-xs px-2 py-0.5 rounded bg-slate-700 text-slate-300">
                          {error.assignedAgent}
                        </span>
                        <span className="text-xs text-slate-500">
                          {new Date(error.timestamp).toLocaleTimeString()}
                        </span>
                      </div>
                    </div>
                    <button onClick={stryMutAct_9fa48("4402") ? () => undefined : (stryCov_9fa48("4402"), () => handleRequestFix(error.id))} disabled={loadingFixes.has(error.id)} className={`px-3 py-1.5 rounded text-xs font-medium transition-colors flex items-center gap-1.5 ${loadingFixes.has(error.id) ? 'bg-cyan-500/10 text-cyan-400/50 cursor-wait' : 'bg-cyan-500/20 text-cyan-400 hover:bg-cyan-500/30'}`}>
                      {loadingFixes.has(error.id) ? <>
                          <Loader2 size={12} className="animate-spin" />
                          Fixing...
                        </> : 'Fix'}
                    </button>
                  </div>
                </div>))}
          </div>)}

        {stryMutAct_9fa48("4409") ? activeTab === 'fixes' || <div className="space-y-2">
            {fixes.length === 0 ? <div className="text-center py-8 text-slate-400">
                <FileText size={32} className="mx-auto mb-2" />
                <p>No fixes generated yet</p>
              </div> : fixes.slice().reverse().map(fix => <div key={fix.id} className="p-3 rounded-lg bg-slate-800/50 border border-slate-700/50">
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <p className="text-sm text-white">{fix.description.substring(0, 100)}</p>
                      <div className="flex items-center gap-2 mt-2 flex-wrap">
                        <span className="text-xs px-2 py-0.5 rounded bg-slate-700 text-slate-300">
                          {fix.agentCode}
                        </span>
                        <span className={`text-xs px-2 py-0.5 rounded ${fix.riskLevel === 'safe' ? 'bg-green-500/20 text-green-400' : fix.riskLevel === 'moderate' ? 'bg-yellow-500/20 text-yellow-400' : 'bg-red-500/20 text-red-400'}`}>
                          {fix.riskLevel}
                        </span>
                        <span className="text-xs text-slate-500">
                          {Math.round(fix.confidence * 100)}% confidence
                        </span>
                        <button onClick={() => window.open(`/cortex/intelligence/chronos?timestamp=${new Date((fix as any).timestamp || Date.now()).toISOString()}`, '_blank')} className="text-[10px] px-1.5 py-0.5 rounded bg-cyan-500/10 text-cyan-400 hover:bg-cyan-500/20 transition-colors" title="View when this error occurred in Chronos">
                          ⏱️ View in Chronos
                        </button>
                      </div>
                    </div>
                    {fix.requiresReview && <button onClick={() => AutoHealService.approveFix(fix.id)} className="px-2 py-1 rounded bg-green-500/20 text-green-400 text-xs hover:bg-green-500/30 transition-colors">
                        Approve
                      </button>}
                  </div>
                </div>)}
          </div> : stryMutAct_9fa48("4408") ? false : stryMutAct_9fa48("4407") ? true : (stryCov_9fa48("4407", "4408", "4409"), (stryMutAct_9fa48("4411") ? activeTab !== 'fixes' : stryMutAct_9fa48("4410") ? true : (stryCov_9fa48("4410", "4411"), activeTab === 'fixes')) && <div className="space-y-2">
            {(stryMutAct_9fa48("4415") ? fixes.length !== 0 : stryMutAct_9fa48("4414") ? false : stryMutAct_9fa48("4413") ? true : (stryCov_9fa48("4413", "4414", "4415"), fixes.length === 0)) ? <div className="text-center py-8 text-slate-400">
                <FileText size={32} className="mx-auto mb-2" />
                <p>No fixes generated yet</p>
              </div> : stryMutAct_9fa48("4417") ? fixes.reverse().map(fix => <div key={fix.id} className="p-3 rounded-lg bg-slate-800/50 border border-slate-700/50">
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <p className="text-sm text-white">{fix.description.substring(0, 100)}</p>
                      <div className="flex items-center gap-2 mt-2 flex-wrap">
                        <span className="text-xs px-2 py-0.5 rounded bg-slate-700 text-slate-300">
                          {fix.agentCode}
                        </span>
                        <span className={`text-xs px-2 py-0.5 rounded ${fix.riskLevel === 'safe' ? 'bg-green-500/20 text-green-400' : fix.riskLevel === 'moderate' ? 'bg-yellow-500/20 text-yellow-400' : 'bg-red-500/20 text-red-400'}`}>
                          {fix.riskLevel}
                        </span>
                        <span className="text-xs text-slate-500">
                          {Math.round(fix.confidence * 100)}% confidence
                        </span>
                        <button onClick={() => window.open(`/cortex/intelligence/chronos?timestamp=${new Date((fix as any).timestamp || Date.now()).toISOString()}`, '_blank')} className="text-[10px] px-1.5 py-0.5 rounded bg-cyan-500/10 text-cyan-400 hover:bg-cyan-500/20 transition-colors" title="View when this error occurred in Chronos">
                          ⏱️ View in Chronos
                        </button>
                      </div>
                    </div>
                    {fix.requiresReview && <button onClick={() => AutoHealService.approveFix(fix.id)} className="px-2 py-1 rounded bg-green-500/20 text-green-400 text-xs hover:bg-green-500/30 transition-colors">
                        Approve
                      </button>}
                  </div>
                </div>) : stryMutAct_9fa48("4416") ? fixes.slice().map(fix => <div key={fix.id} className="p-3 rounded-lg bg-slate-800/50 border border-slate-700/50">
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <p className="text-sm text-white">{fix.description.substring(0, 100)}</p>
                      <div className="flex items-center gap-2 mt-2 flex-wrap">
                        <span className="text-xs px-2 py-0.5 rounded bg-slate-700 text-slate-300">
                          {fix.agentCode}
                        </span>
                        <span className={`text-xs px-2 py-0.5 rounded ${fix.riskLevel === 'safe' ? 'bg-green-500/20 text-green-400' : fix.riskLevel === 'moderate' ? 'bg-yellow-500/20 text-yellow-400' : 'bg-red-500/20 text-red-400'}`}>
                          {fix.riskLevel}
                        </span>
                        <span className="text-xs text-slate-500">
                          {Math.round(fix.confidence * 100)}% confidence
                        </span>
                        <button onClick={() => window.open(`/cortex/intelligence/chronos?timestamp=${new Date((fix as any).timestamp || Date.now()).toISOString()}`, '_blank')} className="text-[10px] px-1.5 py-0.5 rounded bg-cyan-500/10 text-cyan-400 hover:bg-cyan-500/20 transition-colors" title="View when this error occurred in Chronos">
                          ⏱️ View in Chronos
                        </button>
                      </div>
                    </div>
                    {fix.requiresReview && <button onClick={() => AutoHealService.approveFix(fix.id)} className="px-2 py-1 rounded bg-green-500/20 text-green-400 text-xs hover:bg-green-500/30 transition-colors">
                        Approve
                      </button>}
                  </div>
                </div>) : (stryCov_9fa48("4416", "4417"), fixes.slice().reverse().map(stryMutAct_9fa48("4418") ? () => undefined : (stryCov_9fa48("4418"), fix => <div key={fix.id} className="p-3 rounded-lg bg-slate-800/50 border border-slate-700/50">
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <p className="text-sm text-white">{stryMutAct_9fa48("4419") ? fix.description : (stryCov_9fa48("4419"), fix.description.substring(0, 100))}</p>
                      <div className="flex items-center gap-2 mt-2 flex-wrap">
                        <span className="text-xs px-2 py-0.5 rounded bg-slate-700 text-slate-300">
                          {fix.agentCode}
                        </span>
                        <span className={`text-xs px-2 py-0.5 rounded ${(stryMutAct_9fa48("4423") ? fix.riskLevel !== 'safe' : stryMutAct_9fa48("4422") ? false : stryMutAct_9fa48("4421") ? true : (stryCov_9fa48("4421", "4422", "4423"), fix.riskLevel === 'safe')) ? 'bg-green-500/20 text-green-400' : (stryMutAct_9fa48("4428") ? fix.riskLevel !== 'moderate' : stryMutAct_9fa48("4427") ? false : stryMutAct_9fa48("4426") ? true : (stryCov_9fa48("4426", "4427", "4428"), fix.riskLevel === 'moderate')) ? 'bg-yellow-500/20 text-yellow-400' : 'bg-red-500/20 text-red-400'}`}>
                          {fix.riskLevel}
                        </span>
                        <span className="text-xs text-slate-500">
                          {Math.round(stryMutAct_9fa48("4432") ? fix.confidence / 100 : (stryCov_9fa48("4432"), fix.confidence * 100))}% confidence
                        </span>
                        <button onClick={stryMutAct_9fa48("4433") ? () => undefined : (stryCov_9fa48("4433"), () => window.open(`/cortex/intelligence/chronos?timestamp=${new Date(stryMutAct_9fa48("4437") ? (fix as any).timestamp && Date.now() : stryMutAct_9fa48("4436") ? false : stryMutAct_9fa48("4435") ? true : (stryCov_9fa48("4435", "4436", "4437"), (fix as any).timestamp || Date.now())).toISOString()}`, '_blank'))} className="text-[10px] px-1.5 py-0.5 rounded bg-cyan-500/10 text-cyan-400 hover:bg-cyan-500/20 transition-colors" title="View when this error occurred in Chronos">
                          ⏱️ View in Chronos
                        </button>
                      </div>
                    </div>
                    {stryMutAct_9fa48("4441") ? fix.requiresReview || <button onClick={() => AutoHealService.approveFix(fix.id)} className="px-2 py-1 rounded bg-green-500/20 text-green-400 text-xs hover:bg-green-500/30 transition-colors">
                        Approve
                      </button> : stryMutAct_9fa48("4440") ? false : stryMutAct_9fa48("4439") ? true : (stryCov_9fa48("4439", "4440", "4441"), fix.requiresReview && <button onClick={stryMutAct_9fa48("4442") ? () => undefined : (stryCov_9fa48("4442"), () => AutoHealService.approveFix(fix.id))} className="px-2 py-1 rounded bg-green-500/20 text-green-400 text-xs hover:bg-green-500/30 transition-colors">
                        Approve
                      </button>)}
                  </div>
                </div>)))}
          </div>)}

        {stryMutAct_9fa48("4445") ? activeTab === 'settings' || <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-white">Auto-Heal Enabled</p>
                <p className="text-xs text-slate-400">Automatically process and fix errors</p>
                <p className="text-[10px] text-amber-400/70 mt-0.5">⚠️ In sovereign mode, auto-heal remains off unless explicitly enabled</p>
              </div>
              <button onClick={() => handleConfigChange({
            autoHealEnabled: !config.autoHealEnabled
          })} className={`w-12 h-6 rounded-full transition-colors ${config.autoHealEnabled ? 'bg-cyan-500' : 'bg-slate-600'}`}>
                <div className={`w-5 h-5 rounded-full bg-white shadow transition-transform ${config.autoHealEnabled ? 'translate-x-6' : 'translate-x-0.5'}`} />
              </button>
            </div>

            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-white">Require Approval</p>
                <p className="text-xs text-slate-400">Review fixes before applying</p>
              </div>
              <button onClick={() => handleConfigChange({
            requireApproval: !config.requireApproval
          })} className={`w-12 h-6 rounded-full transition-colors ${config.requireApproval ? 'bg-cyan-500' : 'bg-slate-600'}`}>
                <div className={`w-5 h-5 rounded-full bg-white shadow transition-transform ${config.requireApproval ? 'translate-x-6' : 'translate-x-0.5'}`} />
              </button>
            </div>

            <div>
              <p className="text-sm font-medium text-white mb-2">Auto-Fix Severity Threshold</p>
              <div className="flex gap-2">
                {(['critical', 'high', 'medium', 'all'] as const).map(level => <button key={level} onClick={() => handleConfigChange({
              autoFixSeverity: level
            })} className={`px-3 py-1.5 rounded text-xs font-medium transition-colors ${config.autoFixSeverity === level ? 'bg-cyan-500 text-white' : 'bg-slate-700 text-slate-300 hover:bg-slate-600'}`}>
                    {level}
                  </button>)}
              </div>
            </div>

            <div>
              <p className="text-sm font-medium text-white mb-2">Max Fixes Per Hour</p>
              <input type="range" min="1" max="50" value={config.maxAutoFixesPerHour} onChange={e => handleConfigChange({
            maxAutoFixesPerHour: parseInt(e.target.value)
          })} className="w-full" />
              <p className="text-xs text-slate-400 mt-1">{config.maxAutoFixesPerHour} fixes/hour</p>
            </div>

            <button onClick={() => AutoHealService.clearQueue()} className="w-full py-2 rounded-lg bg-red-500/20 text-red-400 text-sm font-medium hover:bg-red-500/30 transition-colors">
              Clear Error Queue
            </button>
          </div> : stryMutAct_9fa48("4444") ? false : stryMutAct_9fa48("4443") ? true : (stryCov_9fa48("4443", "4444", "4445"), (stryMutAct_9fa48("4447") ? activeTab !== 'settings' : stryMutAct_9fa48("4446") ? true : (stryCov_9fa48("4446", "4447"), activeTab === 'settings')) && <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-white">Auto-Heal Enabled</p>
                <p className="text-xs text-slate-400">Automatically process and fix errors</p>
                <p className="text-[10px] text-amber-400/70 mt-0.5">⚠️ In sovereign mode, auto-heal remains off unless explicitly enabled</p>
              </div>
              <button onClick={stryMutAct_9fa48("4449") ? () => undefined : (stryCov_9fa48("4449"), () => handleConfigChange(stryMutAct_9fa48("4450") ? {} : (stryCov_9fa48("4450"), {
            autoHealEnabled: stryMutAct_9fa48("4451") ? config.autoHealEnabled : (stryCov_9fa48("4451"), !config.autoHealEnabled)
          })))} className={`w-12 h-6 rounded-full transition-colors ${config.autoHealEnabled ? 'bg-cyan-500' : 'bg-slate-600'}`}>
                <div className={`w-5 h-5 rounded-full bg-white shadow transition-transform ${config.autoHealEnabled ? 'translate-x-6' : 'translate-x-0.5'}`} />
              </button>
            </div>

            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm font-medium text-white">Require Approval</p>
                <p className="text-xs text-slate-400">Review fixes before applying</p>
              </div>
              <button onClick={stryMutAct_9fa48("4458") ? () => undefined : (stryCov_9fa48("4458"), () => handleConfigChange(stryMutAct_9fa48("4459") ? {} : (stryCov_9fa48("4459"), {
            requireApproval: stryMutAct_9fa48("4460") ? config.requireApproval : (stryCov_9fa48("4460"), !config.requireApproval)
          })))} className={`w-12 h-6 rounded-full transition-colors ${config.requireApproval ? 'bg-cyan-500' : 'bg-slate-600'}`}>
                <div className={`w-5 h-5 rounded-full bg-white shadow transition-transform ${config.requireApproval ? 'translate-x-6' : 'translate-x-0.5'}`} />
              </button>
            </div>

            <div>
              <p className="text-sm font-medium text-white mb-2">Auto-Fix Severity Threshold</p>
              <div className="flex gap-2">
                {(['critical', 'high', 'medium', 'all'] as const).map(stryMutAct_9fa48("4467") ? () => undefined : (stryCov_9fa48("4467"), level => <button key={level} onClick={stryMutAct_9fa48("4468") ? () => undefined : (stryCov_9fa48("4468"), () => handleConfigChange(stryMutAct_9fa48("4469") ? {} : (stryCov_9fa48("4469"), {
              autoFixSeverity: level
            })))} className={`px-3 py-1.5 rounded text-xs font-medium transition-colors ${(stryMutAct_9fa48("4473") ? config.autoFixSeverity !== level : stryMutAct_9fa48("4472") ? false : stryMutAct_9fa48("4471") ? true : (stryCov_9fa48("4471", "4472", "4473"), config.autoFixSeverity === level)) ? 'bg-cyan-500 text-white' : 'bg-slate-700 text-slate-300 hover:bg-slate-600'}`}>
                    {level}
                  </button>))}
              </div>
            </div>

            <div>
              <p className="text-sm font-medium text-white mb-2">Max Fixes Per Hour</p>
              <input type="range" min="1" max="50" value={config.maxAutoFixesPerHour} onChange={stryMutAct_9fa48("4476") ? () => undefined : (stryCov_9fa48("4476"), e => handleConfigChange(stryMutAct_9fa48("4477") ? {} : (stryCov_9fa48("4477"), {
            maxAutoFixesPerHour: parseInt(e.target.value)
          })))} className="w-full" />
              <p className="text-xs text-slate-400 mt-1">{config.maxAutoFixesPerHour} fixes/hour</p>
            </div>

            <button onClick={stryMutAct_9fa48("4478") ? () => undefined : (stryCov_9fa48("4478"), () => AutoHealService.clearQueue())} className="w-full py-2 rounded-lg bg-red-500/20 text-red-400 text-sm font-medium hover:bg-red-500/30 transition-colors">
              Clear Error Queue
            </button>
          </div>)}
      </div>
    </div>;
};
export default TechTeamPanel;